[project]
name = "mlipx-hub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dvc-s3>=3.2.0",
    "mlipx[models]",
    "torch-dftd>=0.5.1",
]

[tool.uv.sources]
mlipx = { path = "../../../../data/fzills/tools/mlipx", editable = true }
