[project]
name = "mlipx-hub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dvc-s3>=3.2.0",
    "huggingface-hub[cli]>=0.32.2",
    "mlipx",
]

[tool.uv.sources]
mlipx = { git = "https://github.com/basf/mlipx" }
