stages:
  7net-0_0_RelaxAdsorptionConfigs:
    cmd: zntrack run mlipx.nodes.adsorption.RelaxAdsorptionConfigs --name 7net-0_0_RelaxAdsorptionConfigs
    deps:
    - nodes/initialize/BuildASEslab/frames.traj
    - nodes/initialize/Smiles2Conformers/frames.xyz
    metrics:
    - nodes/7net-0/0/RelaxAdsorptionConfigs/ads_energies.json
    - nodes/7net-0/0/RelaxAdsorptionConfigs/node-meta.json:
        cache: true
    outs:
    - nodes/7net-0/0/RelaxAdsorptionConfigs/frames.traj
    - nodes/7net-0/0/RelaxAdsorptionConfigs/relax
    params:
    - 7net-0_0_RelaxAdsorptionConfigs
  7net-mf-ompa-mpa_0_RelaxAdsorptionConfigs:
    cmd: zntrack run mlipx.nodes.adsorption.RelaxAdsorptionConfigs --name 7net-mf-ompa-mpa_0_RelaxAdsorptionConfigs
    deps:
    - nodes/initialize/BuildASEslab/frames.traj
    - nodes/initialize/Smiles2Conformers/frames.xyz
    metrics:
    - nodes/7net-mf-ompa-mpa/0/RelaxAdsorptionConfigs/ads_energies.json
    - nodes/7net-mf-ompa-mpa/0/RelaxAdsorptionConfigs/node-meta.json:
        cache: true
    outs:
    - nodes/7net-mf-ompa-mpa/0/RelaxAdsorptionConfigs/frames.traj
    - nodes/7net-mf-ompa-mpa/0/RelaxAdsorptionConfigs/relax
    params:
    - 7net-mf-ompa-mpa_0_RelaxAdsorptionConfigs
  grace-2l-omat_0_RelaxAdsorptionConfigs:
    cmd: zntrack run mlipx.nodes.adsorption.RelaxAdsorptionConfigs --name grace-2l-omat_0_RelaxAdsorptionConfigs
    deps:
    - nodes/initialize/BuildASEslab/frames.traj
    - nodes/initialize/Smiles2Conformers/frames.xyz
    metrics:
    - nodes/grace-2l-omat/0/RelaxAdsorptionConfigs/ads_energies.json
    - nodes/grace-2l-omat/0/RelaxAdsorptionConfigs/node-meta.json:
        cache: true
    outs:
    - nodes/grace-2l-omat/0/RelaxAdsorptionConfigs/frames.traj
    - nodes/grace-2l-omat/0/RelaxAdsorptionConfigs/relax
    params:
    - grace-2l-omat_0_RelaxAdsorptionConfigs
  initialize_BuildASEslab:
    cmd: zntrack run mlipx.nodes.adsorption.BuildASEslab --name initialize_BuildASEslab
    metrics:
    - nodes/initialize/BuildASEslab/node-meta.json:
        cache: true
    outs:
    - nodes/initialize/BuildASEslab/frames.traj
    params:
    - initialize_BuildASEslab
  initialize_Smiles2Conformers:
    cmd: zntrack run mlipx.nodes.smiles.Smiles2Conformers --name initialize_Smiles2Conformers
    metrics:
    - nodes/initialize/Smiles2Conformers/node-meta.json:
        cache: true
    outs:
    - nodes/initialize/Smiles2Conformers/frames.xyz
    params:
    - initialize_Smiles2Conformers
  mace-mpa-0_0_RelaxAdsorptionConfigs:
    cmd: zntrack run mlipx.nodes.adsorption.RelaxAdsorptionConfigs --name mace-mpa-0_0_RelaxAdsorptionConfigs
    deps:
    - nodes/initialize/BuildASEslab/frames.traj
    - nodes/initialize/Smiles2Conformers/frames.xyz
    metrics:
    - nodes/mace-mpa-0/0/RelaxAdsorptionConfigs/ads_energies.json
    - nodes/mace-mpa-0/0/RelaxAdsorptionConfigs/node-meta.json:
        cache: true
    outs:
    - nodes/mace-mpa-0/0/RelaxAdsorptionConfigs/frames.traj
    - nodes/mace-mpa-0/0/RelaxAdsorptionConfigs/relax
    params:
    - mace-mpa-0_0_RelaxAdsorptionConfigs
  mattersim_0_RelaxAdsorptionConfigs:
    cmd: zntrack run mlipx.nodes.adsorption.RelaxAdsorptionConfigs --name mattersim_0_RelaxAdsorptionConfigs
    deps:
    - nodes/initialize/BuildASEslab/frames.traj
    - nodes/initialize/Smiles2Conformers/frames.xyz
    metrics:
    - nodes/mattersim/0/RelaxAdsorptionConfigs/ads_energies.json
    - nodes/mattersim/0/RelaxAdsorptionConfigs/node-meta.json:
        cache: true
    outs:
    - nodes/mattersim/0/RelaxAdsorptionConfigs/frames.traj
    - nodes/mattersim/0/RelaxAdsorptionConfigs/relax
    params:
    - mattersim_0_RelaxAdsorptionConfigs
  orb-v2_0_RelaxAdsorptionConfigs:
    cmd: zntrack run mlipx.nodes.adsorption.RelaxAdsorptionConfigs --name orb-v2_0_RelaxAdsorptionConfigs
    deps:
    - nodes/initialize/BuildASEslab/frames.traj
    - nodes/initialize/Smiles2Conformers/frames.xyz
    metrics:
    - nodes/orb-v2/0/RelaxAdsorptionConfigs/ads_energies.json
    - nodes/orb-v2/0/RelaxAdsorptionConfigs/node-meta.json:
        cache: true
    outs:
    - nodes/orb-v2/0/RelaxAdsorptionConfigs/frames.traj
    - nodes/orb-v2/0/RelaxAdsorptionConfigs/relax
    params:
    - orb-v2_0_RelaxAdsorptionConfigs
  orb-v3_0_RelaxAdsorptionConfigs:
    cmd: zntrack run mlipx.nodes.adsorption.RelaxAdsorptionConfigs --name orb-v3_0_RelaxAdsorptionConfigs
    deps:
    - nodes/initialize/BuildASEslab/frames.traj
    - nodes/initialize/Smiles2Conformers/frames.xyz
    metrics:
    - nodes/orb-v3/0/RelaxAdsorptionConfigs/ads_energies.json
    - nodes/orb-v3/0/RelaxAdsorptionConfigs/node-meta.json:
        cache: true
    outs:
    - nodes/orb-v3/0/RelaxAdsorptionConfigs/frames.traj
    - nodes/orb-v3/0/RelaxAdsorptionConfigs/relax
    params:
    - orb-v3_0_RelaxAdsorptionConfigs
