7net-0_0_RelaxAdsorptionConfigs:
  adsorbate_id: -1
  fmax: 0.05
  height: 2.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  mol_index: 0
  optimizer: LBFGS
  position: all
  slab_id: -1
  steps: 300
7net-mf-ompa-mpa_0_RelaxAdsorptionConfigs:
  adsorbate_id: -1
  fmax: 0.05
  height: 2.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      modal: mpa
      model: 7net-mf-ompa
    module: sevenn.sevennet_calculator
  mol_index: 0
  optimizer: LBFGS
  position: all
  slab_id: -1
  steps: 300
grace-2l-omat_0_RelaxAdsorptionConfigs:
  adsorbate_id: -1
  fmax: 0.05
  height: 2.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: TPCalculator
    device: null
    kwargs:
      model: ../../models/GRACE-2L-OMAT
    module: tensorpotential.calculator
  mol_index: 0
  optimizer: LBFGS
  position: all
  slab_id: -1
  steps: 300
initialize_BuildASEslab:
  a: null
  c: false
  crystal: fcc111
  orthogonal: true
  periodic: true
  size:
  - 3
  - 4
  - 4
  symbol: Cu
  vacuum: 10
initialize_Smiles2Conformers:
  max_attempts: 1000
  num_confs: 1
  random_seed: 42
  smiles: CCO
mace-mpa-0_0_RelaxAdsorptionConfigs:
  adsorbate_id: -1
  fmax: 0.05
  height: 2.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: ../../models/mace-mpa-0-medium.model
    module: mace.calculators
  mol_index: 0
  optimizer: LBFGS
  position: all
  slab_id: -1
  steps: 300
mattersim_0_RelaxAdsorptionConfigs:
  adsorbate_id: -1
  fmax: 0.05
  height: 2.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MatterSimCalculator
    device: auto
    kwargs: null
    module: mattersim.forcefield
  mol_index: 0
  optimizer: LBFGS
  position: all
  slab_id: -1
  steps: 300
orb-v2_0_RelaxAdsorptionConfigs:
  adsorbate_id: -1
  fmax: 0.05
  height: 2.1
  model:
    _cls: models.OrbCalc
    device: auto
    kwargs: {}
    name: orb_v2
  mol_index: 0
  optimizer: LBFGS
  position: all
  slab_id: -1
  steps: 300
orb-v3_0_RelaxAdsorptionConfigs:
  adsorbate_id: -1
  fmax: 0.05
  height: 2.1
  model:
    _cls: models.OrbCalc
    device: auto
    kwargs: {}
    name: orb_v3_conservative_inf_omat
  mol_index: 0
  optimizer: LBFGS
  position: all
  slab_id: -1
  steps: 300
