plots:
- mace_mp_0_MolecularDynamics_plots_0:
    x:
      nodes/mace_mp/0/MolecularDynamics/plots.csv: step
    y:
      nodes/mace_mp/0/MolecularDynamics/plots.csv: energy
- mace_mp_0_MolecularDynamics_plots_1:
    x:
      nodes/mace_mp/0/MolecularDynamics/plots.csv: step
    y:
      nodes/mace_mp/0/MolecularDynamics/plots.csv: fmax
- sevennet_0_MolecularDynamics_plots_0:
    x:
      nodes/sevennet/0/MolecularDynamics/plots.csv: step
    y:
      nodes/sevennet/0/MolecularDynamics/plots.csv: energy
- sevennet_0_MolecularDynamics_plots_1:
    x:
      nodes/sevennet/0/MolecularDynamics/plots.csv: step
    y:
      nodes/sevennet/0/MolecularDynamics/plots.csv: fmax
- orb_v2_0_MolecularDynamics_plots_0:
    x:
      nodes/orb_v2/0/MolecularDynamics/plots.csv: step
    y:
      nodes/orb_v2/0/MolecularDynamics/plots.csv: energy
- orb_v2_0_MolecularDynamics_plots_1:
    x:
      nodes/orb_v2/0/MolecularDynamics/plots.csv: step
    y:
      nodes/orb_v2/0/MolecularDynamics/plots.csv: fmax
- chgnet_0_MolecularDynamics_plots_0:
    x:
      nodes/chgnet/0/MolecularDynamics/plots.csv: step
    y:
      nodes/chgnet/0/MolecularDynamics/plots.csv: energy
- chgnet_0_MolecularDynamics_plots_1:
    x:
      nodes/chgnet/0/MolecularDynamics/plots.csv: step
    y:
      nodes/chgnet/0/MolecularDynamics/plots.csv: fmax
stages:
  chgnet_0_MolecularDynamics:
    cmd: zntrack run mlipx.nodes.molecular_dynamics.MolecularDynamics --name chgnet_0_MolecularDynamics
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/chgnet/0/MolecularDynamics/node-meta.json:
        cache: false
    - nodes/chgnet/0/MolecularDynamics/observer_metrics.json:
        cache: false
    outs:
    - nodes/chgnet/0/MolecularDynamics/frames.xyz
    - nodes/chgnet/0/MolecularDynamics/plots.csv
    params:
    - chgnet_0_MolecularDynamics
  initialize_MPRester:
    cmd: zntrack run mlipx.nodes.mp_api.MPRester --name initialize_MPRester
    metrics:
    - nodes/initialize/MPRester/node-meta.json:
        cache: false
    outs:
    - nodes/initialize/MPRester/frames.xyz
    params:
    - initialize_MPRester
  mace_mp_0_MolecularDynamics:
    cmd: zntrack run mlipx.nodes.molecular_dynamics.MolecularDynamics --name mace_mp_0_MolecularDynamics
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/mace_mp/0/MolecularDynamics/node-meta.json:
        cache: false
    - nodes/mace_mp/0/MolecularDynamics/observer_metrics.json:
        cache: false
    outs:
    - nodes/mace_mp/0/MolecularDynamics/frames.xyz
    - nodes/mace_mp/0/MolecularDynamics/plots.csv
    params:
    - mace_mp_0_MolecularDynamics
  orb_v2_0_MolecularDynamics:
    cmd: zntrack run mlipx.nodes.molecular_dynamics.MolecularDynamics --name orb_v2_0_MolecularDynamics
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/orb_v2/0/MolecularDynamics/node-meta.json:
        cache: false
    - nodes/orb_v2/0/MolecularDynamics/observer_metrics.json:
        cache: false
    outs:
    - nodes/orb_v2/0/MolecularDynamics/frames.xyz
    - nodes/orb_v2/0/MolecularDynamics/plots.csv
    params:
    - orb_v2_0_MolecularDynamics
  sevennet_0_MolecularDynamics:
    cmd: zntrack run mlipx.nodes.molecular_dynamics.MolecularDynamics --name sevennet_0_MolecularDynamics
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/sevennet/0/MolecularDynamics/node-meta.json:
        cache: false
    - nodes/sevennet/0/MolecularDynamics/observer_metrics.json:
        cache: false
    outs:
    - nodes/sevennet/0/MolecularDynamics/frames.xyz
    - nodes/sevennet/0/MolecularDynamics/plots.csv
    params:
    - sevennet_0_MolecularDynamics
