plots:
- mace_mp_0_StructureOptimization_plots_0:
    x:
      nodes/mace_mp/0/StructureOptimization/plots.csv: step
    y:
      nodes/mace_mp/0/StructureOptimization/plots.csv: energy
- mace_mp_0_StructureOptimization_plots_1:
    x:
      nodes/mace_mp/0/StructureOptimization/plots.csv: step
    y:
      nodes/mace_mp/0/StructureOptimization/plots.csv: fmax
- sevennet_0_StructureOptimization_plots_0:
    x:
      nodes/sevennet/0/StructureOptimization/plots.csv: step
    y:
      nodes/sevennet/0/StructureOptimization/plots.csv: energy
- sevennet_0_StructureOptimization_plots_1:
    x:
      nodes/sevennet/0/StructureOptimization/plots.csv: step
    y:
      nodes/sevennet/0/StructureOptimization/plots.csv: fmax
- orb_v2_0_StructureOptimization_plots_0:
    x:
      nodes/orb_v2/0/StructureOptimization/plots.csv: step
    y:
      nodes/orb_v2/0/StructureOptimization/plots.csv: energy
- orb_v2_0_StructureOptimization_plots_1:
    x:
      nodes/orb_v2/0/StructureOptimization/plots.csv: step
    y:
      nodes/orb_v2/0/StructureOptimization/plots.csv: fmax
- chgnet_0_StructureOptimization_plots_0:
    x:
      nodes/chgnet/0/StructureOptimization/plots.csv: step
    y:
      nodes/chgnet/0/StructureOptimization/plots.csv: energy
- chgnet_0_StructureOptimization_plots_1:
    x:
      nodes/chgnet/0/StructureOptimization/plots.csv: step
    y:
      nodes/chgnet/0/StructureOptimization/plots.csv: fmax
- mattersim_0_StructureOptimization_plots_0:
    x:
      nodes/mattersim/0/StructureOptimization/plots.csv: step
    y:
      nodes/mattersim/0/StructureOptimization/plots.csv: energy
- mattersim_0_StructureOptimization_plots_1:
    x:
      nodes/mattersim/0/StructureOptimization/plots.csv: step
    y:
      nodes/mattersim/0/StructureOptimization/plots.csv: fmax
stages:
  chgnet_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      chgnet_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/chgnet/0/StructureOptimization/node-meta.json:
        cache: false
    outs:
    - nodes/chgnet/0/StructureOptimization/frames.traj
    - nodes/chgnet/0/StructureOptimization/plots.csv
    params:
    - chgnet_0_StructureOptimization
  initialize_MPRester:
    cmd: zntrack run mlipx.nodes.mp_api.MPRester --name initialize_MPRester
    metrics:
    - nodes/initialize/MPRester/node-meta.json:
        cache: false
    outs:
    - nodes/initialize/MPRester/frames.xyz
    params:
    - initialize_MPRester
  initialize_Rattle:
    cmd: zntrack run mlipx.nodes.rattle.Rattle --name initialize_Rattle
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/initialize/Rattle/node-meta.json:
        cache: false
    outs:
    - nodes/initialize/Rattle/frames.xyz
    params:
    - initialize_Rattle
  mace_mp_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      mace_mp_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/mace_mp/0/StructureOptimization/node-meta.json:
        cache: false
    outs:
    - nodes/mace_mp/0/StructureOptimization/frames.traj
    - nodes/mace_mp/0/StructureOptimization/plots.csv
    params:
    - mace_mp_0_StructureOptimization
  mattersim_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      mattersim_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/mattersim/0/StructureOptimization/node-meta.json:
        cache: false
    outs:
    - nodes/mattersim/0/StructureOptimization/frames.traj
    - nodes/mattersim/0/StructureOptimization/plots.csv
    params:
    - mattersim_0_StructureOptimization
  orb_v2_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      orb_v2_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/orb_v2/0/StructureOptimization/node-meta.json:
        cache: false
    outs:
    - nodes/orb_v2/0/StructureOptimization/frames.traj
    - nodes/orb_v2/0/StructureOptimization/plots.csv
    params:
    - orb_v2_0_StructureOptimization
  sevennet_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      sevennet_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/sevennet/0/StructureOptimization/node-meta.json:
        cache: false
    outs:
    - nodes/sevennet/0/StructureOptimization/frames.traj
    - nodes/sevennet/0/StructureOptimization/plots.csv
    params:
    - sevennet_0_StructureOptimization
