plots:
- mace-mpa-0_NEBs_results:
    x:
      nodes/mace-mpa-0/NEBs/results.csv: data_id
    y:
      nodes/mace-mpa-0/NEBs/results.csv: potential_energy
- 7net-0_NEBs_results:
    x:
      nodes/7net-0/NEBs/results.csv: data_id
    y:
      nodes/7net-0/NEBs/results.csv: potential_energy
- 7net-mf-ompa-mpa_NEBs_results:
    x:
      nodes/7net-mf-ompa-mpa/NEBs/results.csv: data_id
    y:
      nodes/7net-mf-ompa-mpa/NEBs/results.csv: potential_energy
- mattersim_NEBs_results:
    x:
      nodes/mattersim/NEBs/results.csv: data_id
    y:
      nodes/mattersim/NEBs/results.csv: potential_energy
- grace-2l-omat_NEBs_results:
    x:
      nodes/grace-2l-omat/NEBs/results.csv: data_id
    y:
      nodes/grace-2l-omat/NEBs/results.csv: potential_energy
- chgnet_NEBs_results:
    x:
      nodes/chgnet/NEBs/results.csv: data_id
    y:
      nodes/chgnet/NEBs/results.csv: potential_energy
stages:
  7net-0_NEBs:
    cmd: zntrack run mlipx.nodes.nebs.NEBs --name 7net-0_NEBs
    deps:
    - nodes/initialize/NEBinterpolate/initial_frames.xyz
    metrics:
    - nodes/7net-0/NEBs/node-meta.json:
        cache: true
    outs:
    - nodes/7net-0/NEBs/frames.xyz
    - nodes/7net-0/NEBs/neb_trajectory.traj
    - nodes/7net-0/NEBs/results.csv
    params:
    - 7net-0_NEBs
  7net-mf-ompa-mpa_NEBs:
    cmd: zntrack run mlipx.nodes.nebs.NEBs --name 7net-mf-ompa-mpa_NEBs
    deps:
    - nodes/initialize/NEBinterpolate/initial_frames.xyz
    metrics:
    - nodes/7net-mf-ompa-mpa/NEBs/node-meta.json:
        cache: true
    outs:
    - nodes/7net-mf-ompa-mpa/NEBs/frames.xyz
    - nodes/7net-mf-ompa-mpa/NEBs/neb_trajectory.traj
    - nodes/7net-mf-ompa-mpa/NEBs/results.csv
    params:
    - 7net-mf-ompa-mpa_NEBs
  chgnet_NEBs:
    cmd: zntrack run mlipx.nodes.nebs.NEBs --name chgnet_NEBs
    deps:
    - nodes/initialize/NEBinterpolate/initial_frames.xyz
    metrics:
    - nodes/chgnet/NEBs/node-meta.json:
        cache: true
    outs:
    - nodes/chgnet/NEBs/frames.xyz
    - nodes/chgnet/NEBs/neb_trajectory.traj
    - nodes/chgnet/NEBs/results.csv
    params:
    - chgnet_NEBs
  grace-2l-omat_NEBs:
    cmd: zntrack run mlipx.nodes.nebs.NEBs --name grace-2l-omat_NEBs
    deps:
    - nodes/initialize/NEBinterpolate/initial_frames.xyz
    metrics:
    - nodes/grace-2l-omat/NEBs/node-meta.json:
        cache: true
    outs:
    - nodes/grace-2l-omat/NEBs/frames.xyz
    - nodes/grace-2l-omat/NEBs/neb_trajectory.traj
    - nodes/grace-2l-omat/NEBs/results.csv
    params:
    - grace-2l-omat_NEBs
  initialize_LoadDataFile:
    cmd: zntrack run mlipx.nodes.io.LoadDataFile --name initialize_LoadDataFile
    deps:
    - ../../data/neb_end_p.xyz
    metrics:
    - nodes/initialize/LoadDataFile/node-meta.json:
        cache: true
    params:
    - initialize_LoadDataFile
  initialize_NEBinterpolate:
    cmd: zntrack run mlipx.nodes.nebs.NEBinterpolate --name initialize_NEBinterpolate
    deps:
    - nodes/initialize/LoadDataFile/node-meta.json
    metrics:
    - nodes/initialize/NEBinterpolate/node-meta.json:
        cache: true
    outs:
    - nodes/initialize/NEBinterpolate/initial_frames.xyz
    params:
    - initialize_NEBinterpolate
  mace-mpa-0_NEBs:
    cmd: zntrack run mlipx.nodes.nebs.NEBs --name mace-mpa-0_NEBs
    deps:
    - nodes/initialize/NEBinterpolate/initial_frames.xyz
    metrics:
    - nodes/mace-mpa-0/NEBs/node-meta.json:
        cache: true
    outs:
    - nodes/mace-mpa-0/NEBs/frames.xyz
    - nodes/mace-mpa-0/NEBs/neb_trajectory.traj
    - nodes/mace-mpa-0/NEBs/results.csv
    params:
    - mace-mpa-0_NEBs
  mattersim_NEBs:
    cmd: zntrack run mlipx.nodes.nebs.NEBs --name mattersim_NEBs
    deps:
    - nodes/initialize/NEBinterpolate/initial_frames.xyz
    metrics:
    - nodes/mattersim/NEBs/node-meta.json:
        cache: true
    outs:
    - nodes/mattersim/NEBs/frames.xyz
    - nodes/mattersim/NEBs/neb_trajectory.traj
    - nodes/mattersim/NEBs/results.csv
    params:
    - mattersim_NEBs
