plots:
- MACE-MPA-0_NEBs_results:
    x:
      nodes/MACE-MPA-0/NEBs/results.csv: data_id
    y:
      nodes/MACE-MPA-0/NEBs/results.csv: potential_energy
- 7net-0_NEBs_results:
    x:
      nodes/7net-0/NEBs/results.csv: data_id
    y:
      nodes/7net-0/NEBs/results.csv: potential_energy
- 7net-mf-ompa-mpa_NEBs_results:
    x:
      nodes/7net-mf-ompa-mpa/NEBs/results.csv: data_id
    y:
      nodes/7net-mf-ompa-mpa/NEBs/results.csv: potential_energy
- orb-v2_NEBs_results:
    x:
      nodes/orb-v2/NEBs/results.csv: data_id
    y:
      nodes/orb-v2/NEBs/results.csv: potential_energy
- orb-v3_NEBs_results:
    x:
      nodes/orb-v3/NEBs/results.csv: data_id
    y:
      nodes/orb-v3/NEBs/results.csv: potential_energy
- mattersim_NEBs_results:
    x:
      nodes/mattersim/NEBs/results.csv: data_id
    y:
      nodes/mattersim/NEBs/results.csv: potential_energy
- orca_NEBs_results:
    x:
      nodes/orca/NEBs/results.csv: data_id
    y:
      nodes/orca/NEBs/results.csv: potential_energy
- GRACE-2L-OMAT_NEBs_results:
    x:
      nodes/GRACE-2L-OMAT/NEBs/results.csv: data_id
    y:
      nodes/GRACE-2L-OMAT/NEBs/results.csv: potential_energy
- chgnet_NEBs_results:
    x:
      nodes/chgnet/NEBs/results.csv: data_id
    y:
      nodes/chgnet/NEBs/results.csv: potential_energy
stages:
  7net-0_NEBs:
    cmd: zntrack run mlipx.nodes.nebs.NEBs --name 7net-0_NEBs
    deps:
    - nodes/initialize/NEBinterpolate/initial_frames.xyz
    metrics:
    - nodes/7net-0/NEBs/node-meta.json:
        cache: true
    outs:
    - nodes/7net-0/NEBs/frames.xyz
    - nodes/7net-0/NEBs/neb_trajectory.traj
    - nodes/7net-0/NEBs/results.csv
    params:
    - 7net-0_NEBs
  7net-mf-ompa-mpa_NEBs:
    cmd: zntrack run mlipx.nodes.nebs.NEBs --name 7net-mf-ompa-mpa_NEBs
    deps:
    - nodes/initialize/NEBinterpolate/initial_frames.xyz
    metrics:
    - nodes/7net-mf-ompa-mpa/NEBs/node-meta.json:
        cache: true
    outs:
    - nodes/7net-mf-ompa-mpa/NEBs/frames.xyz
    - nodes/7net-mf-ompa-mpa/NEBs/neb_trajectory.traj
    - nodes/7net-mf-ompa-mpa/NEBs/results.csv
    params:
    - 7net-mf-ompa-mpa_NEBs
  GRACE-2L-OMAT_NEBs:
    cmd: zntrack run mlipx.nodes.nebs.NEBs --name GRACE-2L-OMAT_NEBs
    deps:
    - nodes/initialize/NEBinterpolate/initial_frames.xyz
    metrics:
    - nodes/GRACE-2L-OMAT/NEBs/node-meta.json:
        cache: true
    outs:
    - nodes/GRACE-2L-OMAT/NEBs/frames.xyz
    - nodes/GRACE-2L-OMAT/NEBs/neb_trajectory.traj
    - nodes/GRACE-2L-OMAT/NEBs/results.csv
    params:
    - GRACE-2L-OMAT_NEBs
  MACE-MPA-0_NEBs:
    cmd: zntrack run mlipx.nodes.nebs.NEBs --name MACE-MPA-0_NEBs
    deps:
    - nodes/initialize/NEBinterpolate/initial_frames.xyz
    metrics:
    - nodes/MACE-MPA-0/NEBs/node-meta.json:
        cache: true
    outs:
    - nodes/MACE-MPA-0/NEBs/frames.xyz
    - nodes/MACE-MPA-0/NEBs/neb_trajectory.traj
    - nodes/MACE-MPA-0/NEBs/results.csv
    params:
    - MACE-MPA-0_NEBs
  chgnet_NEBs:
    cmd: zntrack run mlipx.nodes.nebs.NEBs --name chgnet_NEBs
    deps:
    - nodes/initialize/NEBinterpolate/initial_frames.xyz
    metrics:
    - nodes/chgnet/NEBs/node-meta.json:
        cache: true
    outs:
    - nodes/chgnet/NEBs/frames.xyz
    - nodes/chgnet/NEBs/neb_trajectory.traj
    - nodes/chgnet/NEBs/results.csv
    params:
    - chgnet_NEBs
  initialize_LoadDataFile:
    cmd: zntrack run mlipx.nodes.io.LoadDataFile --name initialize_LoadDataFile
    deps:
    - ../../data/neb_end_p.xyz
    metrics:
    - nodes/initialize/LoadDataFile/node-meta.json:
        cache: true
    params:
    - initialize_LoadDataFile
  initialize_NEBinterpolate:
    cmd: zntrack run mlipx.nodes.nebs.NEBinterpolate --name initialize_NEBinterpolate
    deps:
    - nodes/initialize/LoadDataFile/node-meta.json
    metrics:
    - nodes/initialize/NEBinterpolate/node-meta.json:
        cache: true
    outs:
    - nodes/initialize/NEBinterpolate/initial_frames.xyz
    params:
    - initialize_NEBinterpolate
  mattersim_NEBs:
    cmd: zntrack run mlipx.nodes.nebs.NEBs --name mattersim_NEBs
    deps:
    - nodes/initialize/NEBinterpolate/initial_frames.xyz
    metrics:
    - nodes/mattersim/NEBs/node-meta.json:
        cache: true
    outs:
    - nodes/mattersim/NEBs/frames.xyz
    - nodes/mattersim/NEBs/neb_trajectory.traj
    - nodes/mattersim/NEBs/results.csv
    params:
    - mattersim_NEBs
  orb-v2_NEBs:
    cmd: zntrack run mlipx.nodes.nebs.NEBs --name orb-v2_NEBs
    deps:
    - nodes/initialize/NEBinterpolate/initial_frames.xyz
    metrics:
    - nodes/orb-v2/NEBs/node-meta.json:
        cache: true
    outs:
    - nodes/orb-v2/NEBs/frames.xyz
    - nodes/orb-v2/NEBs/neb_trajectory.traj
    - nodes/orb-v2/NEBs/results.csv
    params:
    - orb-v2_NEBs
  orb-v3_NEBs:
    cmd: zntrack run mlipx.nodes.nebs.NEBs --name orb-v3_NEBs
    deps:
    - nodes/initialize/NEBinterpolate/initial_frames.xyz
    metrics:
    - nodes/orb-v3/NEBs/node-meta.json:
        cache: true
    outs:
    - nodes/orb-v3/NEBs/frames.xyz
    - nodes/orb-v3/NEBs/neb_trajectory.traj
    - nodes/orb-v3/NEBs/results.csv
    params:
    - orb-v3_NEBs
  orca_NEBs:
    cmd: zntrack run mlipx.nodes.nebs.NEBs --name orca_NEBs
    deps:
    - nodes/initialize/NEBinterpolate/initial_frames.xyz
    metrics:
    - nodes/orca/NEBs/node-meta.json:
        cache: true
    outs:
    - nodes/orca/NEBs/frames.xyz
    - nodes/orca/NEBs/neb_trajectory.traj
    - nodes/orca/NEBs/results.csv
    params:
    - orca_NEBs
