7net-0_NEBs:
  fmax: 0.05
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  n_steps: 500
  optimizer: FIRE
  relax: true
7net-mf-ompa-mpa_NEBs:
  fmax: 0.05
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      modal: mpa
      model: 7net-mf-ompa
    module: sevenn.sevennet_calculator
  n_steps: 500
  optimizer: FIRE
  relax: true
chgnet_NEBs:
  fmax: 0.05
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: CHGNetCalculator
    device: null
    kwargs: null
    module: chgnet.model
  n_steps: 500
  optimizer: FIRE
  relax: true
grace-2l-omat_NEBs:
  fmax: 0.05
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: TPCalculator
    device: null
    kwargs:
      model: ../../models/GRACE-2L-OMAT
    module: tensorpotential.calculator
  n_steps: 500
  optimizer: FIRE
  relax: true
initialize_LoadDataFile:
  start: 0
  step: 1
  stop: null
initialize_NEBinterpolate:
  add_constraints: true
  mic: true
  n_images: 5
mace-mpa-0_NEBs:
  fmax: 0.05
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: ../../models/mace-mpa-0-medium.model
    module: mace.calculators
  n_steps: 500
  optimizer: FIRE
  relax: true
mattersim_NEBs:
  fmax: 0.05
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MatterSimCalculator
    device: auto
    kwargs: null
    module: mattersim.forcefield
  n_steps: 500
  optimizer: FIRE
  relax: true
