7net-0_md_EinsteinMSD:
  apply_com_transform: true
  sampling_rate: 1
  select: name COM and resname H2O
  timestep: 0.0005
7net-0_md_EinsteinMSD_1:
  apply_com_transform: true
  sampling_rate: 1
  select: name COM and resname Eta
  timestep: 0.0005
7net-0_md_InterRDF:
  apply_com_transform: false
  g1: name H
  g2: name H
  nbins: 1000
  range: auto
7net-0_md_InterRDF_1:
  apply_com_transform: false
  g1: name O
  g2: name H
  nbins: 1000
  range: auto
7net-0_md_InterRDF_2:
  apply_com_transform: false
  g1: name O
  g2: name O
  nbins: 1000
  range: auto
7net-0_md_InterRDF_3:
  apply_com_transform: true
  g1: name COM and resname H2O
  g2: name COM and resname H2O
  nbins: 1000
  range: auto
7net-0_md_InterRDF_4:
  apply_com_transform: true
  g1: name COM and resname H2O
  g2: name COM and resname Eta
  nbins: 1000
  range: auto
7net-0_md_InterRDF_5:
  apply_com_transform: true
  g1: name COM and resname Eta
  g2: name COM and resname Eta
  nbins: 1000
  range: auto
7net-0_md_KinisiSelfDiffusion:
  sampling_rate: 1
  start_dt: 10
  structures:
  - O
  time_step: 0.5
7net-0_md_KinisiSelfDiffusion_1:
  sampling_rate: 1
  start_dt: 10
  structures:
  - CCO
  time_step: 0.5
7net-0_md_MolecularDynamics:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  steps: 100000
  thermostat:
    _cls: mlipx.nodes.molecular_dynamics.LangevinConfig
    friction: 0.05
    temperature: 400
    timestep: 0.5
7net-0_md_SelfDiffusionFromMSD:
  end_time: 40
  start_time: 5.7
7net-0_md_SelfDiffusionFromMSD_1:
  end_time: 40
  start_time: 5.7
7net-0_md_Universe:
  residues:
    Eta: CCO
    H2O: O
7net-0_relax_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  optimizer: LBFGS
  steps: 100000000
MACE-MPA-0_md_EinsteinMSD:
  apply_com_transform: true
  sampling_rate: 1
  select: name COM and resname H2O
  timestep: 0.0005
MACE-MPA-0_md_EinsteinMSD_1:
  apply_com_transform: true
  sampling_rate: 1
  select: name COM and resname Eta
  timestep: 0.0005
MACE-MPA-0_md_InterRDF:
  apply_com_transform: false
  g1: name H
  g2: name H
  nbins: 1000
  range: auto
MACE-MPA-0_md_InterRDF_1:
  apply_com_transform: false
  g1: name O
  g2: name H
  nbins: 1000
  range: auto
MACE-MPA-0_md_InterRDF_2:
  apply_com_transform: false
  g1: name O
  g2: name O
  nbins: 1000
  range: auto
MACE-MPA-0_md_InterRDF_3:
  apply_com_transform: true
  g1: name COM and resname H2O
  g2: name COM and resname H2O
  nbins: 1000
  range: auto
MACE-MPA-0_md_InterRDF_4:
  apply_com_transform: true
  g1: name COM and resname H2O
  g2: name COM and resname Eta
  nbins: 1000
  range: auto
MACE-MPA-0_md_InterRDF_5:
  apply_com_transform: true
  g1: name COM and resname Eta
  g2: name COM and resname Eta
  nbins: 1000
  range: auto
MACE-MPA-0_md_KinisiSelfDiffusion:
  sampling_rate: 1
  start_dt: 10
  structures:
  - O
  time_step: 0.5
MACE-MPA-0_md_KinisiSelfDiffusion_1:
  sampling_rate: 1
  start_dt: 10
  structures:
  - CCO
  time_step: 0.5
MACE-MPA-0_md_MolecularDynamics:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: ../../models/mace-mpa-0-medium.model
    module: mace.calculators
  steps: 100000
  thermostat:
    _cls: mlipx.nodes.molecular_dynamics.LangevinConfig
    friction: 0.05
    temperature: 400
    timestep: 0.5
MACE-MPA-0_md_SelfDiffusionFromMSD:
  end_time: 40
  start_time: 5.7
MACE-MPA-0_md_SelfDiffusionFromMSD_1:
  end_time: 40
  start_time: 5.7
MACE-MPA-0_md_Universe:
  residues:
    Eta: CCO
    H2O: O
MACE-MPA-0_relax_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: ../../models/mace-mpa-0-medium.model
    module: mace.calculators
  optimizer: LBFGS
  steps: 100000000
MACE-OFF_md_EinsteinMSD:
  apply_com_transform: true
  sampling_rate: 1
  select: name COM and resname H2O
  timestep: 0.0005
MACE-OFF_md_EinsteinMSD_1:
  apply_com_transform: true
  sampling_rate: 1
  select: name COM and resname Eta
  timestep: 0.0005
MACE-OFF_md_InterRDF:
  apply_com_transform: false
  g1: name H
  g2: name H
  nbins: 1000
  range: auto
MACE-OFF_md_InterRDF_1:
  apply_com_transform: false
  g1: name O
  g2: name H
  nbins: 1000
  range: auto
MACE-OFF_md_InterRDF_2:
  apply_com_transform: false
  g1: name O
  g2: name O
  nbins: 1000
  range: auto
MACE-OFF_md_InterRDF_3:
  apply_com_transform: true
  g1: name COM and resname H2O
  g2: name COM and resname H2O
  nbins: 1000
  range: auto
MACE-OFF_md_InterRDF_4:
  apply_com_transform: true
  g1: name COM and resname H2O
  g2: name COM and resname Eta
  nbins: 1000
  range: auto
MACE-OFF_md_InterRDF_5:
  apply_com_transform: true
  g1: name COM and resname Eta
  g2: name COM and resname Eta
  nbins: 1000
  range: auto
MACE-OFF_md_KinisiSelfDiffusion:
  sampling_rate: 1
  start_dt: 10
  structures:
  - O
  time_step: 0.5
MACE-OFF_md_KinisiSelfDiffusion_1:
  sampling_rate: 1
  start_dt: 10
  structures:
  - CCO
  time_step: 0.5
MACE-OFF_md_MolecularDynamics:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_off
    device: auto
    kwargs:
      default_dtype: float32
      model: medium
    module: mace.calculators
  steps: 100000
  thermostat:
    _cls: mlipx.nodes.molecular_dynamics.LangevinConfig
    friction: 0.05
    temperature: 400
    timestep: 0.5
MACE-OFF_md_SelfDiffusionFromMSD:
  end_time: 40
  start_time: 5.7
MACE-OFF_md_SelfDiffusionFromMSD_1:
  end_time: 40
  start_time: 5.7
MACE-OFF_md_Universe:
  residues:
    Eta: CCO
    H2O: O
MACE-OFF_relax_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_off
    device: auto
    kwargs:
      default_dtype: float32
      model: medium
    module: mace.calculators
  optimizer: LBFGS
  steps: 100000000
chgnet_md_EinsteinMSD:
  apply_com_transform: true
  sampling_rate: 1
  select: name COM and resname H2O
  timestep: 0.0005
chgnet_md_EinsteinMSD_1:
  apply_com_transform: true
  sampling_rate: 1
  select: name COM and resname Eta
  timestep: 0.0005
chgnet_md_InterRDF:
  apply_com_transform: false
  g1: name H
  g2: name H
  nbins: 1000
  range: auto
chgnet_md_InterRDF_1:
  apply_com_transform: false
  g1: name O
  g2: name H
  nbins: 1000
  range: auto
chgnet_md_InterRDF_2:
  apply_com_transform: false
  g1: name O
  g2: name O
  nbins: 1000
  range: auto
chgnet_md_InterRDF_3:
  apply_com_transform: true
  g1: name COM and resname H2O
  g2: name COM and resname H2O
  nbins: 1000
  range: auto
chgnet_md_InterRDF_4:
  apply_com_transform: true
  g1: name COM and resname H2O
  g2: name COM and resname Eta
  nbins: 1000
  range: auto
chgnet_md_InterRDF_5:
  apply_com_transform: true
  g1: name COM and resname Eta
  g2: name COM and resname Eta
  nbins: 1000
  range: auto
chgnet_md_KinisiSelfDiffusion:
  sampling_rate: 1
  start_dt: 10
  structures:
  - O
  time_step: 0.5
chgnet_md_KinisiSelfDiffusion_1:
  sampling_rate: 1
  start_dt: 10
  structures:
  - CCO
  time_step: 0.5
chgnet_md_MolecularDynamics:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: CHGNetCalculator
    device: null
    kwargs: null
    module: chgnet.model
  steps: 100000
  thermostat:
    _cls: mlipx.nodes.molecular_dynamics.LangevinConfig
    friction: 0.05
    temperature: 400
    timestep: 0.5
chgnet_md_SelfDiffusionFromMSD:
  end_time: 40
  start_time: 5.7
chgnet_md_SelfDiffusionFromMSD_1:
  end_time: 40
  start_time: 5.7
chgnet_md_Universe:
  residues:
    Eta: CCO
    H2O: O
chgnet_relax_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: CHGNetCalculator
    device: null
    kwargs: null
    module: chgnet.model
  optimizer: LBFGS
  steps: 100000000
initialize_BuildBox:
  counts:
  - 32
  - 32
  density: 910
initialize_Smiles2Conformers:
  max_attempts: 1000
  num_confs: 100
  random_seed: 42
  smiles: O
initialize_Smiles2Conformers_1:
  max_attempts: 1000
  num_confs: 100
  random_seed: 42
  smiles: CCO
mace-matpes-pbe-0_md_EinsteinMSD:
  apply_com_transform: true
  sampling_rate: 1
  select: name COM and resname H2O
  timestep: 0.0005
mace-matpes-pbe-0_md_EinsteinMSD_1:
  apply_com_transform: true
  sampling_rate: 1
  select: name COM and resname Eta
  timestep: 0.0005
mace-matpes-pbe-0_md_InterRDF:
  apply_com_transform: false
  g1: name H
  g2: name H
  nbins: 1000
  range: auto
mace-matpes-pbe-0_md_InterRDF_1:
  apply_com_transform: false
  g1: name O
  g2: name H
  nbins: 1000
  range: auto
mace-matpes-pbe-0_md_InterRDF_2:
  apply_com_transform: false
  g1: name O
  g2: name O
  nbins: 1000
  range: auto
mace-matpes-pbe-0_md_InterRDF_3:
  apply_com_transform: true
  g1: name COM and resname H2O
  g2: name COM and resname H2O
  nbins: 1000
  range: auto
mace-matpes-pbe-0_md_InterRDF_4:
  apply_com_transform: true
  g1: name COM and resname H2O
  g2: name COM and resname Eta
  nbins: 1000
  range: auto
mace-matpes-pbe-0_md_InterRDF_5:
  apply_com_transform: true
  g1: name COM and resname Eta
  g2: name COM and resname Eta
  nbins: 1000
  range: auto
mace-matpes-pbe-0_md_KinisiSelfDiffusion:
  sampling_rate: 1
  start_dt: 10
  structures:
  - O
  time_step: 0.5
mace-matpes-pbe-0_md_KinisiSelfDiffusion_1:
  sampling_rate: 1
  start_dt: 10
  structures:
  - CCO
  time_step: 0.5
mace-matpes-pbe-0_md_MolecularDynamics:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: ../../models/mace-matpes-pbe-omat-ft.model
    module: mace.calculators
  steps: 100000
  thermostat:
    _cls: mlipx.nodes.molecular_dynamics.LangevinConfig
    friction: 0.05
    temperature: 400
    timestep: 0.5
mace-matpes-pbe-0_md_SelfDiffusionFromMSD:
  end_time: 40
  start_time: 5.7
mace-matpes-pbe-0_md_SelfDiffusionFromMSD_1:
  end_time: 40
  start_time: 5.7
mace-matpes-pbe-0_md_Universe:
  residues:
    Eta: CCO
    H2O: O
mace-matpes-pbe-0_relax_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: ../../models/mace-matpes-pbe-omat-ft.model
    module: mace.calculators
  optimizer: LBFGS
  steps: 100000000
mattersim_md_EinsteinMSD:
  apply_com_transform: true
  sampling_rate: 1
  select: name COM and resname H2O
  timestep: 0.0005
mattersim_md_EinsteinMSD_1:
  apply_com_transform: true
  sampling_rate: 1
  select: name COM and resname Eta
  timestep: 0.0005
mattersim_md_InterRDF:
  apply_com_transform: false
  g1: name H
  g2: name H
  nbins: 1000
  range: auto
mattersim_md_InterRDF_1:
  apply_com_transform: false
  g1: name O
  g2: name H
  nbins: 1000
  range: auto
mattersim_md_InterRDF_2:
  apply_com_transform: false
  g1: name O
  g2: name O
  nbins: 1000
  range: auto
mattersim_md_InterRDF_3:
  apply_com_transform: true
  g1: name COM and resname H2O
  g2: name COM and resname H2O
  nbins: 1000
  range: auto
mattersim_md_InterRDF_4:
  apply_com_transform: true
  g1: name COM and resname H2O
  g2: name COM and resname Eta
  nbins: 1000
  range: auto
mattersim_md_InterRDF_5:
  apply_com_transform: true
  g1: name COM and resname Eta
  g2: name COM and resname Eta
  nbins: 1000
  range: auto
mattersim_md_KinisiSelfDiffusion:
  sampling_rate: 1
  start_dt: 10
  structures:
  - O
  time_step: 0.5
mattersim_md_KinisiSelfDiffusion_1:
  sampling_rate: 1
  start_dt: 10
  structures:
  - CCO
  time_step: 0.5
mattersim_md_MolecularDynamics:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MatterSimCalculator
    device: auto
    kwargs: null
    module: mattersim.forcefield
  steps: 100000
  thermostat:
    _cls: mlipx.nodes.molecular_dynamics.LangevinConfig
    friction: 0.05
    temperature: 400
    timestep: 0.5
mattersim_md_SelfDiffusionFromMSD:
  end_time: 40
  start_time: 5.7
mattersim_md_SelfDiffusionFromMSD_1:
  end_time: 40
  start_time: 5.7
mattersim_md_Universe:
  residues:
    Eta: CCO
    H2O: O
mattersim_relax_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MatterSimCalculator
    device: auto
    kwargs: null
    module: mattersim.forcefield
  optimizer: LBFGS
  steps: 100000000
orb-v2_md_EinsteinMSD:
  apply_com_transform: true
  sampling_rate: 1
  select: name COM and resname H2O
  timestep: 0.0005
orb-v2_md_EinsteinMSD_1:
  apply_com_transform: true
  sampling_rate: 1
  select: name COM and resname Eta
  timestep: 0.0005
orb-v2_md_InterRDF:
  apply_com_transform: false
  g1: name H
  g2: name H
  nbins: 1000
  range: auto
orb-v2_md_InterRDF_1:
  apply_com_transform: false
  g1: name O
  g2: name H
  nbins: 1000
  range: auto
orb-v2_md_InterRDF_2:
  apply_com_transform: false
  g1: name O
  g2: name O
  nbins: 1000
  range: auto
orb-v2_md_InterRDF_3:
  apply_com_transform: true
  g1: name COM and resname H2O
  g2: name COM and resname H2O
  nbins: 1000
  range: auto
orb-v2_md_InterRDF_4:
  apply_com_transform: true
  g1: name COM and resname H2O
  g2: name COM and resname Eta
  nbins: 1000
  range: auto
orb-v2_md_InterRDF_5:
  apply_com_transform: true
  g1: name COM and resname Eta
  g2: name COM and resname Eta
  nbins: 1000
  range: auto
orb-v2_md_KinisiSelfDiffusion:
  sampling_rate: 1
  start_dt: 10
  structures:
  - O
  time_step: 0.5
orb-v2_md_KinisiSelfDiffusion_1:
  sampling_rate: 1
  start_dt: 10
  structures:
  - CCO
  time_step: 0.5
orb-v2_md_MolecularDynamics:
  data_id: -1
  model:
    _cls: models.OrbCalc
    device: auto
    kwargs: {}
    name: orb_v2
  steps: 100000
  thermostat:
    _cls: mlipx.nodes.molecular_dynamics.LangevinConfig
    friction: 0.05
    temperature: 400
    timestep: 0.5
orb-v2_md_SelfDiffusionFromMSD:
  end_time: 40
  start_time: 5.7
orb-v2_md_SelfDiffusionFromMSD_1:
  end_time: 40
  start_time: 5.7
orb-v2_md_Universe:
  residues:
    Eta: CCO
    H2O: O
orb-v2_relax_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: models.OrbCalc
    device: auto
    kwargs: {}
    name: orb_v2
  optimizer: LBFGS
  steps: 100000000
orb-v3_md_EinsteinMSD:
  apply_com_transform: true
  sampling_rate: 1
  select: name COM and resname H2O
  timestep: 0.0005
orb-v3_md_EinsteinMSD_1:
  apply_com_transform: true
  sampling_rate: 1
  select: name COM and resname Eta
  timestep: 0.0005
orb-v3_md_InterRDF:
  apply_com_transform: false
  g1: name H
  g2: name H
  nbins: 1000
  range: auto
orb-v3_md_InterRDF_1:
  apply_com_transform: false
  g1: name O
  g2: name H
  nbins: 1000
  range: auto
orb-v3_md_InterRDF_2:
  apply_com_transform: false
  g1: name O
  g2: name O
  nbins: 1000
  range: auto
orb-v3_md_InterRDF_3:
  apply_com_transform: true
  g1: name COM and resname H2O
  g2: name COM and resname H2O
  nbins: 1000
  range: auto
orb-v3_md_InterRDF_4:
  apply_com_transform: true
  g1: name COM and resname H2O
  g2: name COM and resname Eta
  nbins: 1000
  range: auto
orb-v3_md_InterRDF_5:
  apply_com_transform: true
  g1: name COM and resname Eta
  g2: name COM and resname Eta
  nbins: 1000
  range: auto
orb-v3_md_KinisiSelfDiffusion:
  sampling_rate: 1
  start_dt: 10
  structures:
  - O
  time_step: 0.5
orb-v3_md_KinisiSelfDiffusion_1:
  sampling_rate: 1
  start_dt: 10
  structures:
  - CCO
  time_step: 0.5
orb-v3_md_MolecularDynamics:
  data_id: -1
  model:
    _cls: models.OrbCalc
    device: auto
    kwargs: {}
    name: orb_v3_conservative_inf_omat
  steps: 100000
  thermostat:
    _cls: mlipx.nodes.molecular_dynamics.LangevinConfig
    friction: 0.05
    temperature: 400
    timestep: 0.5
orb-v3_md_SelfDiffusionFromMSD:
  end_time: 40
  start_time: 5.7
orb-v3_md_SelfDiffusionFromMSD_1:
  end_time: 40
  start_time: 5.7
orb-v3_md_Universe:
  residues:
    Eta: CCO
    H2O: O
orb-v3_relax_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: models.OrbCalc
    device: auto
    kwargs: {}
    name: orb_v3_conservative_inf_omat
  optimizer: LBFGS
  steps: 100000000
pet-mad_md_EinsteinMSD:
  apply_com_transform: true
  sampling_rate: 1
  select: name COM and resname H2O
  timestep: 0.0005
pet-mad_md_EinsteinMSD_1:
  apply_com_transform: true
  sampling_rate: 1
  select: name COM and resname Eta
  timestep: 0.0005
pet-mad_md_InterRDF:
  apply_com_transform: false
  g1: name H
  g2: name H
  nbins: 1000
  range: auto
pet-mad_md_InterRDF_1:
  apply_com_transform: false
  g1: name O
  g2: name H
  nbins: 1000
  range: auto
pet-mad_md_InterRDF_2:
  apply_com_transform: false
  g1: name O
  g2: name O
  nbins: 1000
  range: auto
pet-mad_md_InterRDF_3:
  apply_com_transform: true
  g1: name COM and resname H2O
  g2: name COM and resname H2O
  nbins: 1000
  range: auto
pet-mad_md_InterRDF_4:
  apply_com_transform: true
  g1: name COM and resname H2O
  g2: name COM and resname Eta
  nbins: 1000
  range: auto
pet-mad_md_InterRDF_5:
  apply_com_transform: true
  g1: name COM and resname Eta
  g2: name COM and resname Eta
  nbins: 1000
  range: auto
pet-mad_md_KinisiSelfDiffusion:
  sampling_rate: 1
  start_dt: 10
  structures:
  - O
  time_step: 0.5
pet-mad_md_KinisiSelfDiffusion_1:
  sampling_rate: 1
  start_dt: 10
  structures:
  - CCO
  time_step: 0.5
pet-mad_md_MolecularDynamics:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: PETMADCalculator
    device: null
    kwargs:
      checkpoint_path: ../../models/pet-mad-latest.ckpt
    module: pet_mad.calculator
  steps: 100000
  thermostat:
    _cls: mlipx.nodes.molecular_dynamics.LangevinConfig
    friction: 0.05
    temperature: 400
    timestep: 0.5
pet-mad_md_SelfDiffusionFromMSD:
  end_time: 40
  start_time: 5.7
pet-mad_md_SelfDiffusionFromMSD_1:
  end_time: 40
  start_time: 5.7
pet-mad_md_Universe:
  residues:
    Eta: CCO
    H2O: O
pet-mad_relax_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: PETMADCalculator
    device: null
    kwargs:
      checkpoint_path: ../../models/pet-mad-latest.ckpt
    module: pet_mad.calculator
  optimizer: LBFGS
  steps: 100000000
