plots:
- mace_mp_0_PourbaixDiagram_results:
    x:
      nodes/mace_mp/0/PourbaixDiagram/results.csv: data_id
    y:
      nodes/mace_mp/0/PourbaixDiagram/results.csv: pourbaix_decomposition_energy
- sevennet_0_PourbaixDiagram_results:
    x:
      nodes/sevennet/0/PourbaixDiagram/results.csv: data_id
    y:
      nodes/sevennet/0/PourbaixDiagram/results.csv: pourbaix_decomposition_energy
- orb_v2_0_PourbaixDiagram_results:
    x:
      nodes/orb_v2/0/PourbaixDiagram/results.csv: data_id
    y:
      nodes/orb_v2/0/PourbaixDiagram/results.csv: pourbaix_decomposition_energy
- chgnet_0_PourbaixDiagram_results:
    x:
      nodes/chgnet/0/PourbaixDiagram/results.csv: data_id
    y:
      nodes/chgnet/0/PourbaixDiagram/results.csv: pourbaix_decomposition_energy
- mattersim_0_PourbaixDiagram_results:
    x:
      nodes/mattersim/0/PourbaixDiagram/results.csv: data_id
    y:
      nodes/mattersim/0/PourbaixDiagram/results.csv: pourbaix_decomposition_energy
stages:
  chgnet_0_PourbaixDiagram:
    cmd: zntrack run mlipx.nodes.pourbaix_diagram.PourbaixDiagram --name chgnet_0_PourbaixDiagram
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/chgnet/0/PourbaixDiagram/node-meta.json:
        cache: false
    outs:
    - nodes/chgnet/0/PourbaixDiagram/frames.xyz
    - nodes/chgnet/0/PourbaixDiagram/pourbaix_diagram.json
    - nodes/chgnet/0/PourbaixDiagram/results.csv
    params:
    - chgnet_0_PourbaixDiagram
  initialize_MPRester:
    cmd: zntrack run mlipx.nodes.mp_api.MPRester --name initialize_MPRester
    metrics:
    - nodes/initialize/MPRester/node-meta.json:
        cache: false
    outs:
    - nodes/initialize/MPRester/frames.xyz
    params:
    - initialize_MPRester
  mace_mp_0_PourbaixDiagram:
    cmd: zntrack run mlipx.nodes.pourbaix_diagram.PourbaixDiagram --name mace_mp_0_PourbaixDiagram
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/mace_mp/0/PourbaixDiagram/node-meta.json:
        cache: false
    outs:
    - nodes/mace_mp/0/PourbaixDiagram/frames.xyz
    - nodes/mace_mp/0/PourbaixDiagram/pourbaix_diagram.json
    - nodes/mace_mp/0/PourbaixDiagram/results.csv
    params:
    - mace_mp_0_PourbaixDiagram
  mattersim_0_PourbaixDiagram:
    cmd: zntrack run mlipx.nodes.pourbaix_diagram.PourbaixDiagram --name mattersim_0_PourbaixDiagram
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/mattersim/0/PourbaixDiagram/node-meta.json:
        cache: false
    outs:
    - nodes/mattersim/0/PourbaixDiagram/frames.xyz
    - nodes/mattersim/0/PourbaixDiagram/pourbaix_diagram.json
    - nodes/mattersim/0/PourbaixDiagram/results.csv
    params:
    - mattersim_0_PourbaixDiagram
  orb_v2_0_PourbaixDiagram:
    cmd: zntrack run mlipx.nodes.pourbaix_diagram.PourbaixDiagram --name orb_v2_0_PourbaixDiagram
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/orb_v2/0/PourbaixDiagram/node-meta.json:
        cache: false
    outs:
    - nodes/orb_v2/0/PourbaixDiagram/frames.xyz
    - nodes/orb_v2/0/PourbaixDiagram/pourbaix_diagram.json
    - nodes/orb_v2/0/PourbaixDiagram/results.csv
    params:
    - orb_v2_0_PourbaixDiagram
  sevennet_0_PourbaixDiagram:
    cmd: zntrack run mlipx.nodes.pourbaix_diagram.PourbaixDiagram --name sevennet_0_PourbaixDiagram
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/sevennet/0/PourbaixDiagram/node-meta.json:
        cache: false
    outs:
    - nodes/sevennet/0/PourbaixDiagram/frames.xyz
    - nodes/sevennet/0/PourbaixDiagram/pourbaix_diagram.json
    - nodes/sevennet/0/PourbaixDiagram/results.csv
    params:
    - sevennet_0_PourbaixDiagram
