chgnet_0_PourbaixDiagram:
  V: 1.8
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: CHGNetCalculator
    device: null
    kwargs: null
    module: chgnet.model
  pH: 1.0
  use_gibbs: false
initialize_MPRester:
  search_kwargs:
    material_ids:
    - mp-1143
mace_mp_0_PourbaixDiagram:
  V: 1.8
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: medium
    module: mace.calculators
  pH: 1.0
  use_gibbs: false
orb_v2_0_PourbaixDiagram:
  V: 1.8
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: models.OrbCalc
    device: auto
    name: orb_v2
  pH: 1.0
  use_gibbs: false
sevennet_0_PourbaixDiagram:
  V: 1.8
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  pH: 1.0
  use_gibbs: false
