plots:
- reference_EvaluateCalculatorResults_plots_0:
    x:
      nodes/reference/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/reference/EvaluateCalculatorResults/plots.csv: fmax
- reference_EvaluateCalculatorResults_plots_1:
    x:
      nodes/reference/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/reference/EvaluateCalculatorResults/plots.csv: fnorm
- reference_EvaluateCalculatorResults_plots_2:
    x:
      nodes/reference/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/reference/EvaluateCalculatorResults/plots.csv: energy
- mace-mpa-0_EvaluateCalculatorResults_plots_0:
    x:
      nodes/mace-mpa-0/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/mace-mpa-0/EvaluateCalculatorResults/plots.csv: fmax
- mace-mpa-0_EvaluateCalculatorResults_plots_1:
    x:
      nodes/mace-mpa-0/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/mace-mpa-0/EvaluateCalculatorResults/plots.csv: fnorm
- mace-mpa-0_EvaluateCalculatorResults_plots_2:
    x:
      nodes/mace-mpa-0/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/mace-mpa-0/EvaluateCalculatorResults/plots.csv: energy
- 7net-0_EvaluateCalculatorResults_plots_0:
    x:
      nodes/7net-0/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/7net-0/EvaluateCalculatorResults/plots.csv: fmax
- 7net-0_EvaluateCalculatorResults_plots_1:
    x:
      nodes/7net-0/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/7net-0/EvaluateCalculatorResults/plots.csv: fnorm
- 7net-0_EvaluateCalculatorResults_plots_2:
    x:
      nodes/7net-0/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/7net-0/EvaluateCalculatorResults/plots.csv: energy
- 7net-mf-ompa-mpa_EvaluateCalculatorResults_plots_0:
    x:
      nodes/7net-mf-ompa-mpa/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/7net-mf-ompa-mpa/EvaluateCalculatorResults/plots.csv: fmax
- 7net-mf-ompa-mpa_EvaluateCalculatorResults_plots_1:
    x:
      nodes/7net-mf-ompa-mpa/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/7net-mf-ompa-mpa/EvaluateCalculatorResults/plots.csv: fnorm
- 7net-mf-ompa-mpa_EvaluateCalculatorResults_plots_2:
    x:
      nodes/7net-mf-ompa-mpa/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/7net-mf-ompa-mpa/EvaluateCalculatorResults/plots.csv: energy
- mattersim_EvaluateCalculatorResults_plots_0:
    x:
      nodes/mattersim/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/mattersim/EvaluateCalculatorResults/plots.csv: fmax
- mattersim_EvaluateCalculatorResults_plots_1:
    x:
      nodes/mattersim/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/mattersim/EvaluateCalculatorResults/plots.csv: fnorm
- mattersim_EvaluateCalculatorResults_plots_2:
    x:
      nodes/mattersim/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/mattersim/EvaluateCalculatorResults/plots.csv: energy
- grace-2l-omat_EvaluateCalculatorResults_plots_0:
    x:
      nodes/grace-2l-omat/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/grace-2l-omat/EvaluateCalculatorResults/plots.csv: fmax
- grace-2l-omat_EvaluateCalculatorResults_plots_1:
    x:
      nodes/grace-2l-omat/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/grace-2l-omat/EvaluateCalculatorResults/plots.csv: fnorm
- grace-2l-omat_EvaluateCalculatorResults_plots_2:
    x:
      nodes/grace-2l-omat/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/grace-2l-omat/EvaluateCalculatorResults/plots.csv: energy
- chgnet_EvaluateCalculatorResults_plots_0:
    x:
      nodes/chgnet/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/chgnet/EvaluateCalculatorResults/plots.csv: fmax
- chgnet_EvaluateCalculatorResults_plots_1:
    x:
      nodes/chgnet/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/chgnet/EvaluateCalculatorResults/plots.csv: fnorm
- chgnet_EvaluateCalculatorResults_plots_2:
    x:
      nodes/chgnet/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/chgnet/EvaluateCalculatorResults/plots.csv: energy
stages:
  7net-0_ApplyCalculator:
    cmd: zntrack run mlipx.nodes.apply_calculator.ApplyCalculator --name 7net-0_ApplyCalculator
    deps:
    - nodes/initialize/LoadDataFile/node-meta.json
    metrics:
    - nodes/7net-0/ApplyCalculator/node-meta.json:
        cache: true
    outs:
    - nodes/7net-0/ApplyCalculator/frames.h5
    params:
    - 7net-0_ApplyCalculator
  7net-0_CompareCalculatorResults:
    cmd: zntrack run mlipx.nodes.compare_calculator.CompareCalculatorResults --name
      7net-0_CompareCalculatorResults
    deps:
    - nodes/7net-0/EvaluateCalculatorResults/node-meta.json
    - nodes/7net-0/EvaluateCalculatorResults/plots.csv
    - nodes/reference/EvaluateCalculatorResults/node-meta.json
    - nodes/reference/EvaluateCalculatorResults/plots.csv
    metrics:
    - nodes/7net-0/CompareCalculatorResults/error.json
    - nodes/7net-0/CompareCalculatorResults/node-meta.json:
        cache: true
    - nodes/7net-0/CompareCalculatorResults/rmse.json
    outs:
    - nodes/7net-0/CompareCalculatorResults/plots.csv
  7net-0_EvaluateCalculatorResults:
    cmd: zntrack run mlipx.nodes.evaluate_calculator.EvaluateCalculatorResults --name
      7net-0_EvaluateCalculatorResults
    deps:
    - nodes/7net-0/ApplyCalculator/frames.h5
    metrics:
    - nodes/7net-0/EvaluateCalculatorResults/node-meta.json:
        cache: true
    outs:
    - nodes/7net-0/EvaluateCalculatorResults/plots.csv
  7net-mf-ompa-mpa_ApplyCalculator:
    cmd: zntrack run mlipx.nodes.apply_calculator.ApplyCalculator --name 7net-mf-ompa-mpa_ApplyCalculator
    deps:
    - nodes/initialize/LoadDataFile/node-meta.json
    metrics:
    - nodes/7net-mf-ompa-mpa/ApplyCalculator/node-meta.json:
        cache: true
    outs:
    - nodes/7net-mf-ompa-mpa/ApplyCalculator/frames.h5
    params:
    - 7net-mf-ompa-mpa_ApplyCalculator
  7net-mf-ompa-mpa_CompareCalculatorResults:
    cmd: zntrack run mlipx.nodes.compare_calculator.CompareCalculatorResults --name
      7net-mf-ompa-mpa_CompareCalculatorResults
    deps:
    - nodes/7net-mf-ompa-mpa/EvaluateCalculatorResults/node-meta.json
    - nodes/7net-mf-ompa-mpa/EvaluateCalculatorResults/plots.csv
    - nodes/reference/EvaluateCalculatorResults/node-meta.json
    - nodes/reference/EvaluateCalculatorResults/plots.csv
    metrics:
    - nodes/7net-mf-ompa-mpa/CompareCalculatorResults/error.json
    - nodes/7net-mf-ompa-mpa/CompareCalculatorResults/node-meta.json:
        cache: true
    - nodes/7net-mf-ompa-mpa/CompareCalculatorResults/rmse.json
    outs:
    - nodes/7net-mf-ompa-mpa/CompareCalculatorResults/plots.csv
  7net-mf-ompa-mpa_EvaluateCalculatorResults:
    cmd: zntrack run mlipx.nodes.evaluate_calculator.EvaluateCalculatorResults --name
      7net-mf-ompa-mpa_EvaluateCalculatorResults
    deps:
    - nodes/7net-mf-ompa-mpa/ApplyCalculator/frames.h5
    metrics:
    - nodes/7net-mf-ompa-mpa/EvaluateCalculatorResults/node-meta.json:
        cache: true
    outs:
    - nodes/7net-mf-ompa-mpa/EvaluateCalculatorResults/plots.csv
  chgnet_ApplyCalculator:
    cmd: zntrack run mlipx.nodes.apply_calculator.ApplyCalculator --name chgnet_ApplyCalculator
    deps:
    - nodes/initialize/LoadDataFile/node-meta.json
    metrics:
    - nodes/chgnet/ApplyCalculator/node-meta.json:
        cache: true
    outs:
    - nodes/chgnet/ApplyCalculator/frames.h5
    params:
    - chgnet_ApplyCalculator
  chgnet_CompareCalculatorResults:
    cmd: zntrack run mlipx.nodes.compare_calculator.CompareCalculatorResults --name
      chgnet_CompareCalculatorResults
    deps:
    - nodes/chgnet/EvaluateCalculatorResults/node-meta.json
    - nodes/chgnet/EvaluateCalculatorResults/plots.csv
    - nodes/reference/EvaluateCalculatorResults/node-meta.json
    - nodes/reference/EvaluateCalculatorResults/plots.csv
    metrics:
    - nodes/chgnet/CompareCalculatorResults/error.json
    - nodes/chgnet/CompareCalculatorResults/node-meta.json:
        cache: true
    - nodes/chgnet/CompareCalculatorResults/rmse.json
    outs:
    - nodes/chgnet/CompareCalculatorResults/plots.csv
  chgnet_EvaluateCalculatorResults:
    cmd: zntrack run mlipx.nodes.evaluate_calculator.EvaluateCalculatorResults --name
      chgnet_EvaluateCalculatorResults
    deps:
    - nodes/chgnet/ApplyCalculator/frames.h5
    metrics:
    - nodes/chgnet/EvaluateCalculatorResults/node-meta.json:
        cache: true
    outs:
    - nodes/chgnet/EvaluateCalculatorResults/plots.csv
  grace-2l-omat_ApplyCalculator:
    cmd: zntrack run mlipx.nodes.apply_calculator.ApplyCalculator --name grace-2l-omat_ApplyCalculator
    deps:
    - nodes/initialize/LoadDataFile/node-meta.json
    metrics:
    - nodes/grace-2l-omat/ApplyCalculator/node-meta.json:
        cache: true
    outs:
    - nodes/grace-2l-omat/ApplyCalculator/frames.h5
    params:
    - grace-2l-omat_ApplyCalculator
  grace-2l-omat_CompareCalculatorResults:
    cmd: zntrack run mlipx.nodes.compare_calculator.CompareCalculatorResults --name
      grace-2l-omat_CompareCalculatorResults
    deps:
    - nodes/grace-2l-omat/EvaluateCalculatorResults/node-meta.json
    - nodes/grace-2l-omat/EvaluateCalculatorResults/plots.csv
    - nodes/reference/EvaluateCalculatorResults/node-meta.json
    - nodes/reference/EvaluateCalculatorResults/plots.csv
    metrics:
    - nodes/grace-2l-omat/CompareCalculatorResults/error.json
    - nodes/grace-2l-omat/CompareCalculatorResults/node-meta.json:
        cache: true
    - nodes/grace-2l-omat/CompareCalculatorResults/rmse.json
    outs:
    - nodes/grace-2l-omat/CompareCalculatorResults/plots.csv
  grace-2l-omat_EvaluateCalculatorResults:
    cmd: zntrack run mlipx.nodes.evaluate_calculator.EvaluateCalculatorResults --name
      grace-2l-omat_EvaluateCalculatorResults
    deps:
    - nodes/grace-2l-omat/ApplyCalculator/frames.h5
    metrics:
    - nodes/grace-2l-omat/EvaluateCalculatorResults/node-meta.json:
        cache: true
    outs:
    - nodes/grace-2l-omat/EvaluateCalculatorResults/plots.csv
  initialize_LoadDataFile:
    cmd: zntrack run mlipx.nodes.io.LoadDataFile --name initialize_LoadDataFile
    deps:
    - ../../data/DODH_adsorption_dft.xyz
    metrics:
    - nodes/initialize/LoadDataFile/node-meta.json:
        cache: true
    params:
    - initialize_LoadDataFile
  mace-mpa-0_ApplyCalculator:
    cmd: zntrack run mlipx.nodes.apply_calculator.ApplyCalculator --name mace-mpa-0_ApplyCalculator
    deps:
    - nodes/initialize/LoadDataFile/node-meta.json
    metrics:
    - nodes/mace-mpa-0/ApplyCalculator/node-meta.json:
        cache: true
    outs:
    - nodes/mace-mpa-0/ApplyCalculator/frames.h5
    params:
    - mace-mpa-0_ApplyCalculator
  mace-mpa-0_CompareCalculatorResults:
    cmd: zntrack run mlipx.nodes.compare_calculator.CompareCalculatorResults --name
      mace-mpa-0_CompareCalculatorResults
    deps:
    - nodes/mace-mpa-0/EvaluateCalculatorResults/node-meta.json
    - nodes/mace-mpa-0/EvaluateCalculatorResults/plots.csv
    - nodes/reference/EvaluateCalculatorResults/node-meta.json
    - nodes/reference/EvaluateCalculatorResults/plots.csv
    metrics:
    - nodes/mace-mpa-0/CompareCalculatorResults/error.json
    - nodes/mace-mpa-0/CompareCalculatorResults/node-meta.json:
        cache: true
    - nodes/mace-mpa-0/CompareCalculatorResults/rmse.json
    outs:
    - nodes/mace-mpa-0/CompareCalculatorResults/plots.csv
  mace-mpa-0_EvaluateCalculatorResults:
    cmd: zntrack run mlipx.nodes.evaluate_calculator.EvaluateCalculatorResults --name
      mace-mpa-0_EvaluateCalculatorResults
    deps:
    - nodes/mace-mpa-0/ApplyCalculator/frames.h5
    metrics:
    - nodes/mace-mpa-0/EvaluateCalculatorResults/node-meta.json:
        cache: true
    outs:
    - nodes/mace-mpa-0/EvaluateCalculatorResults/plots.csv
  mattersim_ApplyCalculator:
    cmd: zntrack run mlipx.nodes.apply_calculator.ApplyCalculator --name mattersim_ApplyCalculator
    deps:
    - nodes/initialize/LoadDataFile/node-meta.json
    metrics:
    - nodes/mattersim/ApplyCalculator/node-meta.json:
        cache: true
    outs:
    - nodes/mattersim/ApplyCalculator/frames.h5
    params:
    - mattersim_ApplyCalculator
  mattersim_CompareCalculatorResults:
    cmd: zntrack run mlipx.nodes.compare_calculator.CompareCalculatorResults --name
      mattersim_CompareCalculatorResults
    deps:
    - nodes/mattersim/EvaluateCalculatorResults/node-meta.json
    - nodes/mattersim/EvaluateCalculatorResults/plots.csv
    - nodes/reference/EvaluateCalculatorResults/node-meta.json
    - nodes/reference/EvaluateCalculatorResults/plots.csv
    metrics:
    - nodes/mattersim/CompareCalculatorResults/error.json
    - nodes/mattersim/CompareCalculatorResults/node-meta.json:
        cache: true
    - nodes/mattersim/CompareCalculatorResults/rmse.json
    outs:
    - nodes/mattersim/CompareCalculatorResults/plots.csv
  mattersim_EvaluateCalculatorResults:
    cmd: zntrack run mlipx.nodes.evaluate_calculator.EvaluateCalculatorResults --name
      mattersim_EvaluateCalculatorResults
    deps:
    - nodes/mattersim/ApplyCalculator/frames.h5
    metrics:
    - nodes/mattersim/EvaluateCalculatorResults/node-meta.json:
        cache: true
    outs:
    - nodes/mattersim/EvaluateCalculatorResults/plots.csv
  reference_EvaluateCalculatorResults:
    cmd: zntrack run mlipx.nodes.evaluate_calculator.EvaluateCalculatorResults --name
      reference_EvaluateCalculatorResults
    deps:
    - nodes/initialize/LoadDataFile/node-meta.json
    metrics:
    - nodes/reference/EvaluateCalculatorResults/node-meta.json:
        cache: true
    outs:
    - nodes/reference/EvaluateCalculatorResults/plots.csv
