plots:
- reference_EvaluateCalculatorResults_plots_0:
    x:
      nodes/reference/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/reference/EvaluateCalculatorResults/plots.csv: fmax
- reference_EvaluateCalculatorResults_plots_1:
    x:
      nodes/reference/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/reference/EvaluateCalculatorResults/plots.csv: fnorm
- reference_EvaluateCalculatorResults_plots_2:
    x:
      nodes/reference/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/reference/EvaluateCalculatorResults/plots.csv: energy
- MACE-MPA-0_EvaluateCalculatorResults_plots_0:
    x:
      nodes/MACE-MPA-0/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/MACE-MPA-0/EvaluateCalculatorResults/plots.csv: fmax
- MACE-MPA-0_EvaluateCalculatorResults_plots_1:
    x:
      nodes/MACE-MPA-0/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/MACE-MPA-0/EvaluateCalculatorResults/plots.csv: fnorm
- MACE-MPA-0_EvaluateCalculatorResults_plots_2:
    x:
      nodes/MACE-MPA-0/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/MACE-MPA-0/EvaluateCalculatorResults/plots.csv: energy
- 7net-0_EvaluateCalculatorResults_plots_0:
    x:
      nodes/7net-0/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/7net-0/EvaluateCalculatorResults/plots.csv: fmax
- 7net-0_EvaluateCalculatorResults_plots_1:
    x:
      nodes/7net-0/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/7net-0/EvaluateCalculatorResults/plots.csv: fnorm
- 7net-0_EvaluateCalculatorResults_plots_2:
    x:
      nodes/7net-0/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/7net-0/EvaluateCalculatorResults/plots.csv: energy
- 7net-mf-ompa-mpa_EvaluateCalculatorResults_plots_0:
    x:
      nodes/7net-mf-ompa-mpa/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/7net-mf-ompa-mpa/EvaluateCalculatorResults/plots.csv: fmax
- 7net-mf-ompa-mpa_EvaluateCalculatorResults_plots_1:
    x:
      nodes/7net-mf-ompa-mpa/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/7net-mf-ompa-mpa/EvaluateCalculatorResults/plots.csv: fnorm
- 7net-mf-ompa-mpa_EvaluateCalculatorResults_plots_2:
    x:
      nodes/7net-mf-ompa-mpa/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/7net-mf-ompa-mpa/EvaluateCalculatorResults/plots.csv: energy
- mattersim_EvaluateCalculatorResults_plots_0:
    x:
      nodes/mattersim/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/mattersim/EvaluateCalculatorResults/plots.csv: fmax
- mattersim_EvaluateCalculatorResults_plots_1:
    x:
      nodes/mattersim/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/mattersim/EvaluateCalculatorResults/plots.csv: fnorm
- mattersim_EvaluateCalculatorResults_plots_2:
    x:
      nodes/mattersim/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/mattersim/EvaluateCalculatorResults/plots.csv: energy
- GRACE-2L-OMAT_EvaluateCalculatorResults_plots_0:
    x:
      nodes/GRACE-2L-OMAT/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/GRACE-2L-OMAT/EvaluateCalculatorResults/plots.csv: fmax
- GRACE-2L-OMAT_EvaluateCalculatorResults_plots_1:
    x:
      nodes/GRACE-2L-OMAT/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/GRACE-2L-OMAT/EvaluateCalculatorResults/plots.csv: fnorm
- GRACE-2L-OMAT_EvaluateCalculatorResults_plots_2:
    x:
      nodes/GRACE-2L-OMAT/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/GRACE-2L-OMAT/EvaluateCalculatorResults/plots.csv: energy
- chgnet_EvaluateCalculatorResults_plots_0:
    x:
      nodes/chgnet/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/chgnet/EvaluateCalculatorResults/plots.csv: fmax
- chgnet_EvaluateCalculatorResults_plots_1:
    x:
      nodes/chgnet/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/chgnet/EvaluateCalculatorResults/plots.csv: fnorm
- chgnet_EvaluateCalculatorResults_plots_2:
    x:
      nodes/chgnet/EvaluateCalculatorResults/plots.csv: step
    y:
      nodes/chgnet/EvaluateCalculatorResults/plots.csv: energy
stages:
  7net-0_ApplyCalculator:
    cmd: zntrack run mlipx.nodes.apply_calculator.ApplyCalculator --name 7net-0_ApplyCalculator
    deps:
    - nodes/initialize/LoadDataFile/node-meta.json
    metrics:
    - nodes/7net-0/ApplyCalculator/node-meta.json:
        cache: true
    outs:
    - nodes/7net-0/ApplyCalculator/frames.h5
    params:
    - 7net-0_ApplyCalculator
  7net-0_CompareCalculatorResults:
    cmd: zntrack run mlipx.nodes.compare_calculator.CompareCalculatorResults --name
      7net-0_CompareCalculatorResults
    deps:
    - nodes/7net-0/EvaluateCalculatorResults/node-meta.json
    - nodes/7net-0/EvaluateCalculatorResults/plots.csv
    - nodes/reference/EvaluateCalculatorResults/node-meta.json
    - nodes/reference/EvaluateCalculatorResults/plots.csv
    metrics:
    - nodes/7net-0/CompareCalculatorResults/error.json
    - nodes/7net-0/CompareCalculatorResults/node-meta.json:
        cache: true
    - nodes/7net-0/CompareCalculatorResults/rmse.json
    outs:
    - nodes/7net-0/CompareCalculatorResults/plots.csv
  7net-0_EvaluateCalculatorResults:
    cmd: zntrack run mlipx.nodes.evaluate_calculator.EvaluateCalculatorResults --name
      7net-0_EvaluateCalculatorResults
    deps:
    - nodes/7net-0/ApplyCalculator/frames.h5
    metrics:
    - nodes/7net-0/EvaluateCalculatorResults/node-meta.json:
        cache: true
    outs:
    - nodes/7net-0/EvaluateCalculatorResults/plots.csv
  7net-mf-ompa-mpa_ApplyCalculator:
    cmd: zntrack run mlipx.nodes.apply_calculator.ApplyCalculator --name 7net-mf-ompa-mpa_ApplyCalculator
    deps:
    - nodes/initialize/LoadDataFile/node-meta.json
    metrics:
    - nodes/7net-mf-ompa-mpa/ApplyCalculator/node-meta.json:
        cache: true
    outs:
    - nodes/7net-mf-ompa-mpa/ApplyCalculator/frames.h5
    params:
    - 7net-mf-ompa-mpa_ApplyCalculator
  7net-mf-ompa-mpa_CompareCalculatorResults:
    cmd: zntrack run mlipx.nodes.compare_calculator.CompareCalculatorResults --name
      7net-mf-ompa-mpa_CompareCalculatorResults
    deps:
    - nodes/7net-mf-ompa-mpa/EvaluateCalculatorResults/node-meta.json
    - nodes/7net-mf-ompa-mpa/EvaluateCalculatorResults/plots.csv
    - nodes/reference/EvaluateCalculatorResults/node-meta.json
    - nodes/reference/EvaluateCalculatorResults/plots.csv
    metrics:
    - nodes/7net-mf-ompa-mpa/CompareCalculatorResults/error.json
    - nodes/7net-mf-ompa-mpa/CompareCalculatorResults/node-meta.json:
        cache: true
    - nodes/7net-mf-ompa-mpa/CompareCalculatorResults/rmse.json
    outs:
    - nodes/7net-mf-ompa-mpa/CompareCalculatorResults/plots.csv
  7net-mf-ompa-mpa_EvaluateCalculatorResults:
    cmd: zntrack run mlipx.nodes.evaluate_calculator.EvaluateCalculatorResults --name
      7net-mf-ompa-mpa_EvaluateCalculatorResults
    deps:
    - nodes/7net-mf-ompa-mpa/ApplyCalculator/frames.h5
    metrics:
    - nodes/7net-mf-ompa-mpa/EvaluateCalculatorResults/node-meta.json:
        cache: true
    outs:
    - nodes/7net-mf-ompa-mpa/EvaluateCalculatorResults/plots.csv
  GRACE-2L-OMAT_ApplyCalculator:
    cmd: zntrack run mlipx.nodes.apply_calculator.ApplyCalculator --name GRACE-2L-OMAT_ApplyCalculator
    deps:
    - nodes/initialize/LoadDataFile/node-meta.json
    metrics:
    - nodes/GRACE-2L-OMAT/ApplyCalculator/node-meta.json:
        cache: true
    outs:
    - nodes/GRACE-2L-OMAT/ApplyCalculator/frames.h5
    params:
    - GRACE-2L-OMAT_ApplyCalculator
  GRACE-2L-OMAT_CompareCalculatorResults:
    cmd: zntrack run mlipx.nodes.compare_calculator.CompareCalculatorResults --name
      GRACE-2L-OMAT_CompareCalculatorResults
    deps:
    - nodes/GRACE-2L-OMAT/EvaluateCalculatorResults/node-meta.json
    - nodes/GRACE-2L-OMAT/EvaluateCalculatorResults/plots.csv
    - nodes/reference/EvaluateCalculatorResults/node-meta.json
    - nodes/reference/EvaluateCalculatorResults/plots.csv
    metrics:
    - nodes/GRACE-2L-OMAT/CompareCalculatorResults/error.json
    - nodes/GRACE-2L-OMAT/CompareCalculatorResults/node-meta.json:
        cache: true
    - nodes/GRACE-2L-OMAT/CompareCalculatorResults/rmse.json
    outs:
    - nodes/GRACE-2L-OMAT/CompareCalculatorResults/plots.csv
  GRACE-2L-OMAT_EvaluateCalculatorResults:
    cmd: zntrack run mlipx.nodes.evaluate_calculator.EvaluateCalculatorResults --name
      GRACE-2L-OMAT_EvaluateCalculatorResults
    deps:
    - nodes/GRACE-2L-OMAT/ApplyCalculator/frames.h5
    metrics:
    - nodes/GRACE-2L-OMAT/EvaluateCalculatorResults/node-meta.json:
        cache: true
    outs:
    - nodes/GRACE-2L-OMAT/EvaluateCalculatorResults/plots.csv
  MACE-MPA-0_ApplyCalculator:
    cmd: zntrack run mlipx.nodes.apply_calculator.ApplyCalculator --name MACE-MPA-0_ApplyCalculator
    deps:
    - nodes/initialize/LoadDataFile/node-meta.json
    metrics:
    - nodes/MACE-MPA-0/ApplyCalculator/node-meta.json:
        cache: true
    outs:
    - nodes/MACE-MPA-0/ApplyCalculator/frames.h5
    params:
    - MACE-MPA-0_ApplyCalculator
  MACE-MPA-0_CompareCalculatorResults:
    cmd: zntrack run mlipx.nodes.compare_calculator.CompareCalculatorResults --name
      MACE-MPA-0_CompareCalculatorResults
    deps:
    - nodes/MACE-MPA-0/EvaluateCalculatorResults/node-meta.json
    - nodes/MACE-MPA-0/EvaluateCalculatorResults/plots.csv
    - nodes/reference/EvaluateCalculatorResults/node-meta.json
    - nodes/reference/EvaluateCalculatorResults/plots.csv
    metrics:
    - nodes/MACE-MPA-0/CompareCalculatorResults/error.json
    - nodes/MACE-MPA-0/CompareCalculatorResults/node-meta.json:
        cache: true
    - nodes/MACE-MPA-0/CompareCalculatorResults/rmse.json
    outs:
    - nodes/MACE-MPA-0/CompareCalculatorResults/plots.csv
  MACE-MPA-0_EvaluateCalculatorResults:
    cmd: zntrack run mlipx.nodes.evaluate_calculator.EvaluateCalculatorResults --name
      MACE-MPA-0_EvaluateCalculatorResults
    deps:
    - nodes/MACE-MPA-0/ApplyCalculator/frames.h5
    metrics:
    - nodes/MACE-MPA-0/EvaluateCalculatorResults/node-meta.json:
        cache: true
    outs:
    - nodes/MACE-MPA-0/EvaluateCalculatorResults/plots.csv
  chgnet_ApplyCalculator:
    cmd: zntrack run mlipx.nodes.apply_calculator.ApplyCalculator --name chgnet_ApplyCalculator
    deps:
    - nodes/initialize/LoadDataFile/node-meta.json
    metrics:
    - nodes/chgnet/ApplyCalculator/node-meta.json:
        cache: true
    outs:
    - nodes/chgnet/ApplyCalculator/frames.h5
    params:
    - chgnet_ApplyCalculator
  chgnet_CompareCalculatorResults:
    cmd: zntrack run mlipx.nodes.compare_calculator.CompareCalculatorResults --name
      chgnet_CompareCalculatorResults
    deps:
    - nodes/chgnet/EvaluateCalculatorResults/node-meta.json
    - nodes/chgnet/EvaluateCalculatorResults/plots.csv
    - nodes/reference/EvaluateCalculatorResults/node-meta.json
    - nodes/reference/EvaluateCalculatorResults/plots.csv
    metrics:
    - nodes/chgnet/CompareCalculatorResults/error.json
    - nodes/chgnet/CompareCalculatorResults/node-meta.json:
        cache: true
    - nodes/chgnet/CompareCalculatorResults/rmse.json
    outs:
    - nodes/chgnet/CompareCalculatorResults/plots.csv
  chgnet_EvaluateCalculatorResults:
    cmd: zntrack run mlipx.nodes.evaluate_calculator.EvaluateCalculatorResults --name
      chgnet_EvaluateCalculatorResults
    deps:
    - nodes/chgnet/ApplyCalculator/frames.h5
    metrics:
    - nodes/chgnet/EvaluateCalculatorResults/node-meta.json:
        cache: true
    outs:
    - nodes/chgnet/EvaluateCalculatorResults/plots.csv
  initialize_LoadDataFile:
    cmd: zntrack run mlipx.nodes.io.LoadDataFile --name initialize_LoadDataFile
    deps:
    - ../../data/DODH_adsorption_dft.xyz
    metrics:
    - nodes/initialize/LoadDataFile/node-meta.json:
        cache: true
    params:
    - initialize_LoadDataFile
  mattersim_ApplyCalculator:
    cmd: zntrack run mlipx.nodes.apply_calculator.ApplyCalculator --name mattersim_ApplyCalculator
    deps:
    - nodes/initialize/LoadDataFile/node-meta.json
    metrics:
    - nodes/mattersim/ApplyCalculator/node-meta.json:
        cache: true
    outs:
    - nodes/mattersim/ApplyCalculator/frames.h5
    params:
    - mattersim_ApplyCalculator
  mattersim_CompareCalculatorResults:
    cmd: zntrack run mlipx.nodes.compare_calculator.CompareCalculatorResults --name
      mattersim_CompareCalculatorResults
    deps:
    - nodes/mattersim/EvaluateCalculatorResults/node-meta.json
    - nodes/mattersim/EvaluateCalculatorResults/plots.csv
    - nodes/reference/EvaluateCalculatorResults/node-meta.json
    - nodes/reference/EvaluateCalculatorResults/plots.csv
    metrics:
    - nodes/mattersim/CompareCalculatorResults/error.json
    - nodes/mattersim/CompareCalculatorResults/node-meta.json:
        cache: true
    - nodes/mattersim/CompareCalculatorResults/rmse.json
    outs:
    - nodes/mattersim/CompareCalculatorResults/plots.csv
  mattersim_EvaluateCalculatorResults:
    cmd: zntrack run mlipx.nodes.evaluate_calculator.EvaluateCalculatorResults --name
      mattersim_EvaluateCalculatorResults
    deps:
    - nodes/mattersim/ApplyCalculator/frames.h5
    metrics:
    - nodes/mattersim/EvaluateCalculatorResults/node-meta.json:
        cache: true
    outs:
    - nodes/mattersim/EvaluateCalculatorResults/plots.csv
  reference_EvaluateCalculatorResults:
    cmd: zntrack run mlipx.nodes.evaluate_calculator.EvaluateCalculatorResults --name
      reference_EvaluateCalculatorResults
    deps:
    - nodes/initialize/LoadDataFile/node-meta.json
    metrics:
    - nodes/reference/EvaluateCalculatorResults/node-meta.json:
        cache: true
    outs:
    - nodes/reference/EvaluateCalculatorResults/plots.csv
