chgnet_ApplyCalculator:
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: CHGNetCalculator
    device: null
    kwargs: null
    module: chgnet.model
initialize_LoadDataFile:
  start: 0
  step: 1
  stop: null
mace_mp_ApplyCalculator:
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: medium
    module: mace.calculators
mattersim_ApplyCalculator:
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MatterSimCalculator
    device: auto
    kwargs: null
    module: mattersim.forcefield
orb_v2_ApplyCalculator:
  model:
    _cls: models.OrbCalc
    device: auto
    name: orb_v2
sevennet_ApplyCalculator:
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
