7net-0_ApplyCalculator:
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
7net-mf-ompa-mpa_ApplyCalculator:
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      modal: mpa
      model: 7net-mf-ompa
    module: sevenn.sevennet_calculator
chgnet_ApplyCalculator:
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: CHGNetCalculator
    device: null
    kwargs: null
    module: chgnet.model
grace-2l-omat_ApplyCalculator:
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: TPCalculator
    device: null
    kwargs:
      model: ../../models/GRACE-2L-OMAT
    module: tensorpotential.calculator
initialize_LoadDataFile:
  start: 0
  step: 1
  stop: null
mace-mpa-0_ApplyCalculator:
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: ../../models/mace-mpa-0-medium.model
    module: mace.calculators
mattersim_ApplyCalculator:
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MatterSimCalculator
    device: auto
    kwargs: null
    module: mattersim.forcefield
