plots:
- MACE-MPA-0_0_MolecularDynamics_plots_0:
    x:
      nodes/MACE-MPA-0/0/MolecularDynamics/plots.csv: step
    y:
      nodes/MACE-MPA-0/0/MolecularDynamics/plots.csv: energy
- MACE-MPA-0_0_MolecularDynamics_plots_1:
    x:
      nodes/MACE-MPA-0/0/MolecularDynamics/plots.csv: step
    y:
      nodes/MACE-MPA-0/0/MolecularDynamics/plots.csv: fmax
- 7net-0_0_MolecularDynamics_plots_0:
    x:
      nodes/7net-0/0/MolecularDynamics/plots.csv: step
    y:
      nodes/7net-0/0/MolecularDynamics/plots.csv: energy
- 7net-0_0_MolecularDynamics_plots_1:
    x:
      nodes/7net-0/0/MolecularDynamics/plots.csv: step
    y:
      nodes/7net-0/0/MolecularDynamics/plots.csv: fmax
- 7net-mf-ompa-mpa_0_MolecularDynamics_plots_0:
    x:
      nodes/7net-mf-ompa-mpa/0/MolecularDynamics/plots.csv: step
    y:
      nodes/7net-mf-ompa-mpa/0/MolecularDynamics/plots.csv: energy
- 7net-mf-ompa-mpa_0_MolecularDynamics_plots_1:
    x:
      nodes/7net-mf-ompa-mpa/0/MolecularDynamics/plots.csv: step
    y:
      nodes/7net-mf-ompa-mpa/0/MolecularDynamics/plots.csv: fmax
- orb-v2_0_MolecularDynamics_plots_0:
    x:
      nodes/orb-v2/0/MolecularDynamics/plots.csv: step
    y:
      nodes/orb-v2/0/MolecularDynamics/plots.csv: energy
- orb-v2_0_MolecularDynamics_plots_1:
    x:
      nodes/orb-v2/0/MolecularDynamics/plots.csv: step
    y:
      nodes/orb-v2/0/MolecularDynamics/plots.csv: fmax
- orb-v3_0_MolecularDynamics_plots_0:
    x:
      nodes/orb-v3/0/MolecularDynamics/plots.csv: step
    y:
      nodes/orb-v3/0/MolecularDynamics/plots.csv: energy
- orb-v3_0_MolecularDynamics_plots_1:
    x:
      nodes/orb-v3/0/MolecularDynamics/plots.csv: step
    y:
      nodes/orb-v3/0/MolecularDynamics/plots.csv: fmax
- mattersim_0_MolecularDynamics_plots_0:
    x:
      nodes/mattersim/0/MolecularDynamics/plots.csv: step
    y:
      nodes/mattersim/0/MolecularDynamics/plots.csv: energy
- mattersim_0_MolecularDynamics_plots_1:
    x:
      nodes/mattersim/0/MolecularDynamics/plots.csv: step
    y:
      nodes/mattersim/0/MolecularDynamics/plots.csv: fmax
- GRACE-2L-OMAT_0_MolecularDynamics_plots_0:
    x:
      nodes/GRACE-2L-OMAT/0/MolecularDynamics/plots.csv: step
    y:
      nodes/GRACE-2L-OMAT/0/MolecularDynamics/plots.csv: energy
- GRACE-2L-OMAT_0_MolecularDynamics_plots_1:
    x:
      nodes/GRACE-2L-OMAT/0/MolecularDynamics/plots.csv: step
    y:
      nodes/GRACE-2L-OMAT/0/MolecularDynamics/plots.csv: fmax
- chgnet_0_MolecularDynamics_plots_0:
    x:
      nodes/chgnet/0/MolecularDynamics/plots.csv: step
    y:
      nodes/chgnet/0/MolecularDynamics/plots.csv: energy
- chgnet_0_MolecularDynamics_plots_1:
    x:
      nodes/chgnet/0/MolecularDynamics/plots.csv: step
    y:
      nodes/chgnet/0/MolecularDynamics/plots.csv: fmax
stages:
  7net-0_0_MolecularDynamics:
    cmd: zntrack run mlipx.nodes.molecular_dynamics.MolecularDynamics --name 7net-0_0_MolecularDynamics
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/7net-0/0/MolecularDynamics/node-meta.json:
        cache: true
    - nodes/7net-0/0/MolecularDynamics/observer_metrics.json
    outs:
    - nodes/7net-0/0/MolecularDynamics/frames.xyz
    - nodes/7net-0/0/MolecularDynamics/plots.csv
    params:
    - 7net-0_0_MolecularDynamics
  7net-mf-ompa-mpa_0_MolecularDynamics:
    cmd: zntrack run mlipx.nodes.molecular_dynamics.MolecularDynamics --name 7net-mf-ompa-mpa_0_MolecularDynamics
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/7net-mf-ompa-mpa/0/MolecularDynamics/node-meta.json:
        cache: true
    - nodes/7net-mf-ompa-mpa/0/MolecularDynamics/observer_metrics.json
    outs:
    - nodes/7net-mf-ompa-mpa/0/MolecularDynamics/frames.xyz
    - nodes/7net-mf-ompa-mpa/0/MolecularDynamics/plots.csv
    params:
    - 7net-mf-ompa-mpa_0_MolecularDynamics
  GRACE-2L-OMAT_0_MolecularDynamics:
    cmd: zntrack run mlipx.nodes.molecular_dynamics.MolecularDynamics --name GRACE-2L-OMAT_0_MolecularDynamics
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/GRACE-2L-OMAT/0/MolecularDynamics/node-meta.json:
        cache: true
    - nodes/GRACE-2L-OMAT/0/MolecularDynamics/observer_metrics.json
    outs:
    - nodes/GRACE-2L-OMAT/0/MolecularDynamics/frames.xyz
    - nodes/GRACE-2L-OMAT/0/MolecularDynamics/plots.csv
    params:
    - GRACE-2L-OMAT_0_MolecularDynamics
  MACE-MPA-0_0_MolecularDynamics:
    cmd: zntrack run mlipx.nodes.molecular_dynamics.MolecularDynamics --name MACE-MPA-0_0_MolecularDynamics
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/MACE-MPA-0/0/MolecularDynamics/node-meta.json:
        cache: true
    - nodes/MACE-MPA-0/0/MolecularDynamics/observer_metrics.json
    outs:
    - nodes/MACE-MPA-0/0/MolecularDynamics/frames.xyz
    - nodes/MACE-MPA-0/0/MolecularDynamics/plots.csv
    params:
    - MACE-MPA-0_0_MolecularDynamics
  chgnet_0_MolecularDynamics:
    cmd: zntrack run mlipx.nodes.molecular_dynamics.MolecularDynamics --name chgnet_0_MolecularDynamics
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/chgnet/0/MolecularDynamics/node-meta.json:
        cache: true
    - nodes/chgnet/0/MolecularDynamics/observer_metrics.json
    outs:
    - nodes/chgnet/0/MolecularDynamics/frames.xyz
    - nodes/chgnet/0/MolecularDynamics/plots.csv
    params:
    - chgnet_0_MolecularDynamics
  initialize_MPRester:
    cmd: zntrack run mlipx.nodes.mp_api.MPRester --name initialize_MPRester
    metrics:
    - nodes/initialize/MPRester/node-meta.json:
        cache: true
    outs:
    - nodes/initialize/MPRester/frames.xyz
    params:
    - initialize_MPRester
  mattersim_0_MolecularDynamics:
    cmd: zntrack run mlipx.nodes.molecular_dynamics.MolecularDynamics --name mattersim_0_MolecularDynamics
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/mattersim/0/MolecularDynamics/node-meta.json:
        cache: true
    - nodes/mattersim/0/MolecularDynamics/observer_metrics.json
    outs:
    - nodes/mattersim/0/MolecularDynamics/frames.xyz
    - nodes/mattersim/0/MolecularDynamics/plots.csv
    params:
    - mattersim_0_MolecularDynamics
  orb-v2_0_MolecularDynamics:
    cmd: zntrack run mlipx.nodes.molecular_dynamics.MolecularDynamics --name orb-v2_0_MolecularDynamics
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/orb-v2/0/MolecularDynamics/node-meta.json:
        cache: true
    - nodes/orb-v2/0/MolecularDynamics/observer_metrics.json
    outs:
    - nodes/orb-v2/0/MolecularDynamics/frames.xyz
    - nodes/orb-v2/0/MolecularDynamics/plots.csv
    params:
    - orb-v2_0_MolecularDynamics
  orb-v3_0_MolecularDynamics:
    cmd: zntrack run mlipx.nodes.molecular_dynamics.MolecularDynamics --name orb-v3_0_MolecularDynamics
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/orb-v3/0/MolecularDynamics/node-meta.json:
        cache: true
    - nodes/orb-v3/0/MolecularDynamics/observer_metrics.json
    outs:
    - nodes/orb-v3/0/MolecularDynamics/frames.xyz
    - nodes/orb-v3/0/MolecularDynamics/plots.csv
    params:
    - orb-v3_0_MolecularDynamics
