7net-0_0_MolecularDynamics:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  modifiers:
  - _cls: mlipx.nodes.modifier.TemperatureRampModifier
    end_temperature: 400
    interval: 1
    start_temperature: null
    total_steps: 100
  observers:
  - _cls: mlipx.nodes.observer.MaximumForceObserver
    f_max: 100
  steps: 1000
  thermostat:
    _cls: mlipx.nodes.molecular_dynamics.LangevinConfig
    friction: 0.05
    temperature: 300
    timestep: 0.5
7net-mf-ompa-mpa_0_MolecularDynamics:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      modal: mpa
      model: 7net-mf-ompa
    module: sevenn.sevennet_calculator
  modifiers:
  - _cls: mlipx.nodes.modifier.TemperatureRampModifier
    end_temperature: 400
    interval: 1
    start_temperature: null
    total_steps: 100
  observers:
  - _cls: mlipx.nodes.observer.MaximumForceObserver
    f_max: 100
  steps: 1000
  thermostat:
    _cls: mlipx.nodes.molecular_dynamics.LangevinConfig
    friction: 0.05
    temperature: 300
    timestep: 0.5
chgnet_0_MolecularDynamics:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: CHGNetCalculator
    device: null
    kwargs: null
    module: chgnet.model
  modifiers:
  - _cls: mlipx.nodes.modifier.TemperatureRampModifier
    end_temperature: 400
    interval: 1
    start_temperature: null
    total_steps: 100
  observers:
  - _cls: mlipx.nodes.observer.MaximumForceObserver
    f_max: 100
  steps: 1000
  thermostat:
    _cls: mlipx.nodes.molecular_dynamics.LangevinConfig
    friction: 0.05
    temperature: 300
    timestep: 0.5
grace-2l-omat_0_MolecularDynamics:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: TPCalculator
    device: null
    kwargs:
      model: ../../models/GRACE-2L-OMAT
    module: tensorpotential.calculator
  modifiers:
  - _cls: mlipx.nodes.modifier.TemperatureRampModifier
    end_temperature: 400
    interval: 1
    start_temperature: null
    total_steps: 100
  observers:
  - _cls: mlipx.nodes.observer.MaximumForceObserver
    f_max: 100
  steps: 1000
  thermostat:
    _cls: mlipx.nodes.molecular_dynamics.LangevinConfig
    friction: 0.05
    temperature: 300
    timestep: 0.5
initialize_MPRester:
  search_kwargs:
    material_ids:
    - mp-1143
mace-mpa-0_0_MolecularDynamics:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: ../../models/mace-mpa-0-medium.model
    module: mace.calculators
  modifiers:
  - _cls: mlipx.nodes.modifier.TemperatureRampModifier
    end_temperature: 400
    interval: 1
    start_temperature: null
    total_steps: 100
  observers:
  - _cls: mlipx.nodes.observer.MaximumForceObserver
    f_max: 100
  steps: 1000
  thermostat:
    _cls: mlipx.nodes.molecular_dynamics.LangevinConfig
    friction: 0.05
    temperature: 300
    timestep: 0.5
mattersim_0_MolecularDynamics:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MatterSimCalculator
    device: auto
    kwargs: null
    module: mattersim.forcefield
  modifiers:
  - _cls: mlipx.nodes.modifier.TemperatureRampModifier
    end_temperature: 400
    interval: 1
    start_temperature: null
    total_steps: 100
  observers:
  - _cls: mlipx.nodes.observer.MaximumForceObserver
    f_max: 100
  steps: 1000
  thermostat:
    _cls: mlipx.nodes.molecular_dynamics.LangevinConfig
    friction: 0.05
    temperature: 300
    timestep: 0.5
orb-v2_0_MolecularDynamics:
  data_id: -1
  model:
    _cls: models.OrbCalc
    device: auto
    kwargs: {}
    name: orb_v2
  modifiers:
  - _cls: mlipx.nodes.modifier.TemperatureRampModifier
    end_temperature: 400
    interval: 1
    start_temperature: null
    total_steps: 100
  observers:
  - _cls: mlipx.nodes.observer.MaximumForceObserver
    f_max: 100
  steps: 1000
  thermostat:
    _cls: mlipx.nodes.molecular_dynamics.LangevinConfig
    friction: 0.05
    temperature: 300
    timestep: 0.5
orb-v3_0_MolecularDynamics:
  data_id: -1
  model:
    _cls: models.OrbCalc
    device: auto
    kwargs: {}
    name: orb_v3_conservative_inf_omat
  modifiers:
  - _cls: mlipx.nodes.modifier.TemperatureRampModifier
    end_temperature: 400
    interval: 1
    start_temperature: null
    total_steps: 100
  observers:
  - _cls: mlipx.nodes.observer.MaximumForceObserver
    f_max: 100
  steps: 1000
  thermostat:
    _cls: mlipx.nodes.molecular_dynamics.LangevinConfig
    friction: 0.05
    temperature: 300
    timestep: 0.5
