plots:
- mace-mpa-0_0_StructureOptimization_plots_0:
    x:
      nodes/mace-mpa-0/0/StructureOptimization/plots.csv: step
    y:
      nodes/mace-mpa-0/0/StructureOptimization/plots.csv: energy
- mace-mpa-0_0_StructureOptimization_plots_1:
    x:
      nodes/mace-mpa-0/0/StructureOptimization/plots.csv: step
    y:
      nodes/mace-mpa-0/0/StructureOptimization/plots.csv: fmax
- 7net-0_0_StructureOptimization_plots_0:
    x:
      nodes/7net-0/0/StructureOptimization/plots.csv: step
    y:
      nodes/7net-0/0/StructureOptimization/plots.csv: energy
- 7net-0_0_StructureOptimization_plots_1:
    x:
      nodes/7net-0/0/StructureOptimization/plots.csv: step
    y:
      nodes/7net-0/0/StructureOptimization/plots.csv: fmax
- 7net-mf-ompa-mpa_0_StructureOptimization_plots_0:
    x:
      nodes/7net-mf-ompa-mpa/0/StructureOptimization/plots.csv: step
    y:
      nodes/7net-mf-ompa-mpa/0/StructureOptimization/plots.csv: energy
- 7net-mf-ompa-mpa_0_StructureOptimization_plots_1:
    x:
      nodes/7net-mf-ompa-mpa/0/StructureOptimization/plots.csv: step
    y:
      nodes/7net-mf-ompa-mpa/0/StructureOptimization/plots.csv: fmax
- orb-v2_0_StructureOptimization_plots_0:
    x:
      nodes/orb-v2/0/StructureOptimization/plots.csv: step
    y:
      nodes/orb-v2/0/StructureOptimization/plots.csv: energy
- orb-v2_0_StructureOptimization_plots_1:
    x:
      nodes/orb-v2/0/StructureOptimization/plots.csv: step
    y:
      nodes/orb-v2/0/StructureOptimization/plots.csv: fmax
- orb-v3_0_StructureOptimization_plots_0:
    x:
      nodes/orb-v3/0/StructureOptimization/plots.csv: step
    y:
      nodes/orb-v3/0/StructureOptimization/plots.csv: energy
- orb-v3_0_StructureOptimization_plots_1:
    x:
      nodes/orb-v3/0/StructureOptimization/plots.csv: step
    y:
      nodes/orb-v3/0/StructureOptimization/plots.csv: fmax
- mattersim_0_StructureOptimization_plots_0:
    x:
      nodes/mattersim/0/StructureOptimization/plots.csv: step
    y:
      nodes/mattersim/0/StructureOptimization/plots.csv: energy
- mattersim_0_StructureOptimization_plots_1:
    x:
      nodes/mattersim/0/StructureOptimization/plots.csv: step
    y:
      nodes/mattersim/0/StructureOptimization/plots.csv: fmax
- grace-2l-omat_0_StructureOptimization_plots_0:
    x:
      nodes/grace-2l-omat/0/StructureOptimization/plots.csv: step
    y:
      nodes/grace-2l-omat/0/StructureOptimization/plots.csv: energy
- grace-2l-omat_0_StructureOptimization_plots_1:
    x:
      nodes/grace-2l-omat/0/StructureOptimization/plots.csv: step
    y:
      nodes/grace-2l-omat/0/StructureOptimization/plots.csv: fmax
- chgnet_0_StructureOptimization_plots_0:
    x:
      nodes/chgnet/0/StructureOptimization/plots.csv: step
    y:
      nodes/chgnet/0/StructureOptimization/plots.csv: energy
- chgnet_0_StructureOptimization_plots_1:
    x:
      nodes/chgnet/0/StructureOptimization/plots.csv: step
    y:
      nodes/chgnet/0/StructureOptimization/plots.csv: fmax
- matpes-pbe_0_StructureOptimization_plots_0:
    x:
      nodes/matpes-pbe/0/StructureOptimization/plots.csv: step
    y:
      nodes/matpes-pbe/0/StructureOptimization/plots.csv: energy
- matpes-pbe_0_StructureOptimization_plots_1:
    x:
      nodes/matpes-pbe/0/StructureOptimization/plots.csv: step
    y:
      nodes/matpes-pbe/0/StructureOptimization/plots.csv: fmax
- meta-uma-sm_0_StructureOptimization_plots_0:
    x:
      nodes/meta-uma-sm/0/StructureOptimization/plots.csv: step
    y:
      nodes/meta-uma-sm/0/StructureOptimization/plots.csv: energy
- meta-uma-sm_0_StructureOptimization_plots_1:
    x:
      nodes/meta-uma-sm/0/StructureOptimization/plots.csv: step
    y:
      nodes/meta-uma-sm/0/StructureOptimization/plots.csv: fmax
- mace-matpes-pbe-0_0_StructureOptimization_plots_0:
    x:
      nodes/mace-matpes-pbe-0/0/StructureOptimization/plots.csv: step
    y:
      nodes/mace-matpes-pbe-0/0/StructureOptimization/plots.csv: energy
- mace-matpes-pbe-0_0_StructureOptimization_plots_1:
    x:
      nodes/mace-matpes-pbe-0/0/StructureOptimization/plots.csv: step
    y:
      nodes/mace-matpes-pbe-0/0/StructureOptimization/plots.csv: fmax
- pet-mad_0_StructureOptimization_plots_0:
    x:
      nodes/pet-mad/0/StructureOptimization/plots.csv: step
    y:
      nodes/pet-mad/0/StructureOptimization/plots.csv: energy
- pet-mad_0_StructureOptimization_plots_1:
    x:
      nodes/pet-mad/0/StructureOptimization/plots.csv: step
    y:
      nodes/pet-mad/0/StructureOptimization/plots.csv: fmax
stages:
  7net-0_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      7net-0_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/7net-0/0/StructureOptimization/node-meta.json:
        cache: true
    outs:
    - nodes/7net-0/0/StructureOptimization/frames.traj
    - nodes/7net-0/0/StructureOptimization/plots.csv
    params:
    - 7net-0_0_StructureOptimization
  7net-mf-ompa-mpa_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      7net-mf-ompa-mpa_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/7net-mf-ompa-mpa/0/StructureOptimization/node-meta.json:
        cache: true
    outs:
    - nodes/7net-mf-ompa-mpa/0/StructureOptimization/frames.traj
    - nodes/7net-mf-ompa-mpa/0/StructureOptimization/plots.csv
    params:
    - 7net-mf-ompa-mpa_0_StructureOptimization
  chgnet_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      chgnet_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/chgnet/0/StructureOptimization/node-meta.json:
        cache: true
    outs:
    - nodes/chgnet/0/StructureOptimization/frames.traj
    - nodes/chgnet/0/StructureOptimization/plots.csv
    params:
    - chgnet_0_StructureOptimization
  grace-2l-omat_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      grace-2l-omat_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/grace-2l-omat/0/StructureOptimization/node-meta.json:
        cache: true
    outs:
    - nodes/grace-2l-omat/0/StructureOptimization/frames.traj
    - nodes/grace-2l-omat/0/StructureOptimization/plots.csv
    params:
    - grace-2l-omat_0_StructureOptimization
  initialize_MPRester:
    cmd: zntrack run mlipx.nodes.mp_api.MPRester --name initialize_MPRester
    metrics:
    - nodes/initialize/MPRester/node-meta.json:
        cache: true
    outs:
    - nodes/initialize/MPRester/frames.xyz
    params:
    - initialize_MPRester
  initialize_Rattle:
    cmd: zntrack run mlipx.nodes.rattle.Rattle --name initialize_Rattle
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/initialize/Rattle/node-meta.json:
        cache: true
    outs:
    - nodes/initialize/Rattle/frames.xyz
    params:
    - initialize_Rattle
  mace-matpes-pbe-0_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      mace-matpes-pbe-0_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/mace-matpes-pbe-0/0/StructureOptimization/node-meta.json:
        cache: true
    outs:
    - nodes/mace-matpes-pbe-0/0/StructureOptimization/frames.traj
    - nodes/mace-matpes-pbe-0/0/StructureOptimization/plots.csv
    params:
    - mace-matpes-pbe-0_0_StructureOptimization
  mace-mpa-0_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      mace-mpa-0_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/mace-mpa-0/0/StructureOptimization/node-meta.json:
        cache: true
    outs:
    - nodes/mace-mpa-0/0/StructureOptimization/frames.traj
    - nodes/mace-mpa-0/0/StructureOptimization/plots.csv
    params:
    - mace-mpa-0_0_StructureOptimization
  matpes-pbe_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      matpes-pbe_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/matpes-pbe/0/StructureOptimization/node-meta.json:
        cache: true
    outs:
    - nodes/matpes-pbe/0/StructureOptimization/frames.traj
    - nodes/matpes-pbe/0/StructureOptimization/plots.csv
    params:
    - matpes-pbe_0_StructureOptimization
  mattersim_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      mattersim_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/mattersim/0/StructureOptimization/node-meta.json:
        cache: true
    outs:
    - nodes/mattersim/0/StructureOptimization/frames.traj
    - nodes/mattersim/0/StructureOptimization/plots.csv
    params:
    - mattersim_0_StructureOptimization
  meta-uma-sm_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      meta-uma-sm_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/meta-uma-sm/0/StructureOptimization/node-meta.json:
        cache: true
    outs:
    - nodes/meta-uma-sm/0/StructureOptimization/frames.traj
    - nodes/meta-uma-sm/0/StructureOptimization/plots.csv
    params:
    - meta-uma-sm_0_StructureOptimization
  orb-v2_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      orb-v2_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/orb-v2/0/StructureOptimization/node-meta.json:
        cache: true
    outs:
    - nodes/orb-v2/0/StructureOptimization/frames.traj
    - nodes/orb-v2/0/StructureOptimization/plots.csv
    params:
    - orb-v2_0_StructureOptimization
  orb-v3_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      orb-v3_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/orb-v3/0/StructureOptimization/node-meta.json:
        cache: true
    outs:
    - nodes/orb-v3/0/StructureOptimization/frames.traj
    - nodes/orb-v3/0/StructureOptimization/plots.csv
    params:
    - orb-v3_0_StructureOptimization
  pet-mad_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      pet-mad_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/pet-mad/0/StructureOptimization/node-meta.json:
        cache: true
    outs:
    - nodes/pet-mad/0/StructureOptimization/frames.traj
    - nodes/pet-mad/0/StructureOptimization/plots.csv
    params:
    - pet-mad_0_StructureOptimization
