plots:
- MACE-MPA-0_0_StructureOptimization_plots_0:
    x:
      nodes/MACE-MPA-0/0/StructureOptimization/plots.csv: step
    y:
      nodes/MACE-MPA-0/0/StructureOptimization/plots.csv: energy
- MACE-MPA-0_0_StructureOptimization_plots_1:
    x:
      nodes/MACE-MPA-0/0/StructureOptimization/plots.csv: step
    y:
      nodes/MACE-MPA-0/0/StructureOptimization/plots.csv: fmax
- 7net-0_0_StructureOptimization_plots_0:
    x:
      nodes/7net-0/0/StructureOptimization/plots.csv: step
    y:
      nodes/7net-0/0/StructureOptimization/plots.csv: energy
- 7net-0_0_StructureOptimization_plots_1:
    x:
      nodes/7net-0/0/StructureOptimization/plots.csv: step
    y:
      nodes/7net-0/0/StructureOptimization/plots.csv: fmax
- 7net-mf-ompa-mpa_0_StructureOptimization_plots_0:
    x:
      nodes/7net-mf-ompa-mpa/0/StructureOptimization/plots.csv: step
    y:
      nodes/7net-mf-ompa-mpa/0/StructureOptimization/plots.csv: energy
- 7net-mf-ompa-mpa_0_StructureOptimization_plots_1:
    x:
      nodes/7net-mf-ompa-mpa/0/StructureOptimization/plots.csv: step
    y:
      nodes/7net-mf-ompa-mpa/0/StructureOptimization/plots.csv: fmax
- orb-v2_0_StructureOptimization_plots_0:
    x:
      nodes/orb-v2/0/StructureOptimization/plots.csv: step
    y:
      nodes/orb-v2/0/StructureOptimization/plots.csv: energy
- orb-v2_0_StructureOptimization_plots_1:
    x:
      nodes/orb-v2/0/StructureOptimization/plots.csv: step
    y:
      nodes/orb-v2/0/StructureOptimization/plots.csv: fmax
- orb-v3_0_StructureOptimization_plots_0:
    x:
      nodes/orb-v3/0/StructureOptimization/plots.csv: step
    y:
      nodes/orb-v3/0/StructureOptimization/plots.csv: energy
- orb-v3_0_StructureOptimization_plots_1:
    x:
      nodes/orb-v3/0/StructureOptimization/plots.csv: step
    y:
      nodes/orb-v3/0/StructureOptimization/plots.csv: fmax
- mattersim_0_StructureOptimization_plots_0:
    x:
      nodes/mattersim/0/StructureOptimization/plots.csv: step
    y:
      nodes/mattersim/0/StructureOptimization/plots.csv: energy
- mattersim_0_StructureOptimization_plots_1:
    x:
      nodes/mattersim/0/StructureOptimization/plots.csv: step
    y:
      nodes/mattersim/0/StructureOptimization/plots.csv: fmax
- GRACE-2L-OMAT_0_StructureOptimization_plots_0:
    x:
      nodes/GRACE-2L-OMAT/0/StructureOptimization/plots.csv: step
    y:
      nodes/GRACE-2L-OMAT/0/StructureOptimization/plots.csv: energy
- GRACE-2L-OMAT_0_StructureOptimization_plots_1:
    x:
      nodes/GRACE-2L-OMAT/0/StructureOptimization/plots.csv: step
    y:
      nodes/GRACE-2L-OMAT/0/StructureOptimization/plots.csv: fmax
- chgnet_0_StructureOptimization_plots_0:
    x:
      nodes/chgnet/0/StructureOptimization/plots.csv: step
    y:
      nodes/chgnet/0/StructureOptimization/plots.csv: energy
- chgnet_0_StructureOptimization_plots_1:
    x:
      nodes/chgnet/0/StructureOptimization/plots.csv: step
    y:
      nodes/chgnet/0/StructureOptimization/plots.csv: fmax
stages:
  7net-0_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      7net-0_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/7net-0/0/StructureOptimization/node-meta.json:
        cache: true
    outs:
    - nodes/7net-0/0/StructureOptimization/frames.traj
    - nodes/7net-0/0/StructureOptimization/plots.csv
    params:
    - 7net-0_0_StructureOptimization
  7net-mf-ompa-mpa_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      7net-mf-ompa-mpa_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/7net-mf-ompa-mpa/0/StructureOptimization/node-meta.json:
        cache: true
    outs:
    - nodes/7net-mf-ompa-mpa/0/StructureOptimization/frames.traj
    - nodes/7net-mf-ompa-mpa/0/StructureOptimization/plots.csv
    params:
    - 7net-mf-ompa-mpa_0_StructureOptimization
  GRACE-2L-OMAT_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      GRACE-2L-OMAT_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/GRACE-2L-OMAT/0/StructureOptimization/node-meta.json:
        cache: true
    outs:
    - nodes/GRACE-2L-OMAT/0/StructureOptimization/frames.traj
    - nodes/GRACE-2L-OMAT/0/StructureOptimization/plots.csv
    params:
    - GRACE-2L-OMAT_0_StructureOptimization
  MACE-MPA-0_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      MACE-MPA-0_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/MACE-MPA-0/0/StructureOptimization/node-meta.json:
        cache: true
    outs:
    - nodes/MACE-MPA-0/0/StructureOptimization/frames.traj
    - nodes/MACE-MPA-0/0/StructureOptimization/plots.csv
    params:
    - MACE-MPA-0_0_StructureOptimization
  chgnet_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      chgnet_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/chgnet/0/StructureOptimization/node-meta.json:
        cache: true
    outs:
    - nodes/chgnet/0/StructureOptimization/frames.traj
    - nodes/chgnet/0/StructureOptimization/plots.csv
    params:
    - chgnet_0_StructureOptimization
  initialize_MPRester:
    cmd: zntrack run mlipx.nodes.mp_api.MPRester --name initialize_MPRester
    metrics:
    - nodes/initialize/MPRester/node-meta.json:
        cache: true
    outs:
    - nodes/initialize/MPRester/frames.xyz
    params:
    - initialize_MPRester
  initialize_Rattle:
    cmd: zntrack run mlipx.nodes.rattle.Rattle --name initialize_Rattle
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/initialize/Rattle/node-meta.json:
        cache: true
    outs:
    - nodes/initialize/Rattle/frames.xyz
    params:
    - initialize_Rattle
  mattersim_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      mattersim_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/mattersim/0/StructureOptimization/node-meta.json:
        cache: true
    outs:
    - nodes/mattersim/0/StructureOptimization/frames.traj
    - nodes/mattersim/0/StructureOptimization/plots.csv
    params:
    - mattersim_0_StructureOptimization
  orb-v2_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      orb-v2_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/orb-v2/0/StructureOptimization/node-meta.json:
        cache: true
    outs:
    - nodes/orb-v2/0/StructureOptimization/frames.traj
    - nodes/orb-v2/0/StructureOptimization/plots.csv
    params:
    - orb-v2_0_StructureOptimization
  orb-v3_0_StructureOptimization:
    cmd: zntrack run mlipx.nodes.structure_optimization.StructureOptimization --name
      orb-v3_0_StructureOptimization
    deps:
    - nodes/initialize/Rattle/frames.xyz
    metrics:
    - nodes/orb-v3/0/StructureOptimization/node-meta.json:
        cache: true
    outs:
    - nodes/orb-v3/0/StructureOptimization/frames.traj
    - nodes/orb-v3/0/StructureOptimization/plots.csv
    params:
    - orb-v3_0_StructureOptimization
