chgnet_0_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: CHGNetCalculator
    device: null
    kwargs: null
    module: chgnet.model
  optimizer: LBFGS
  steps: 100000000
initialize_MPRester:
  search_kwargs:
    material_ids:
    - mp-1143
initialize_Rattle:
  seed: 42
  stdev: 0.1
mace_mp_0_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: medium
    module: mace.calculators
  optimizer: LBFGS
  steps: 100000000
mattersim_0_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MatterSimCalculator
    device: auto
    kwargs: null
    module: mattersim.forcefield
  optimizer: LBFGS
  steps: 100000000
orb_v2_0_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: models.OrbCalc
    device: auto
    name: orb_v2
  optimizer: LBFGS
  steps: 100000000
sevennet_0_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  optimizer: LBFGS
  steps: 100000000
