7net-0_0_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  optimizer: LBFGS
  steps: 100000000
7net-mf-ompa-mpa_0_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      modal: mpa
      model: 7net-mf-ompa
    module: sevenn.sevennet_calculator
  optimizer: LBFGS
  steps: 100000000
chgnet_0_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: CHGNetCalculator
    device: null
    kwargs: null
    module: chgnet.model
  optimizer: LBFGS
  steps: 100000000
grace-2l-omat_0_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: TPCalculator
    device: null
    kwargs:
      model: ../../models/GRACE-2L-OMAT
    module: tensorpotential.calculator
  optimizer: LBFGS
  steps: 100000000
initialize_MPRester:
  search_kwargs:
    material_ids:
    - mp-1143
initialize_Rattle:
  seed: 42
  stdev: 0.1
mace-mpa-0_0_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: ../../models/mace-mpa-0-medium.model
    module: mace.calculators
  optimizer: LBFGS
  steps: 100000000
mattersim_0_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MatterSimCalculator
    device: auto
    kwargs: null
    module: mattersim.forcefield
  optimizer: LBFGS
  steps: 100000000
orb-v2_0_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: models.OrbCalc
    device: auto
    kwargs: {}
    name: orb_v2
  optimizer: LBFGS
  steps: 100000000
orb-v3_0_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: models.OrbCalc
    device: auto
    kwargs: {}
    name: orb_v3_conservative_inf_omat
  optimizer: LBFGS
  steps: 100000000
