stages:
  7net-0_HomonuclearDiatomics:
    cmd: zntrack run mlipx.nodes.diatomics.HomonuclearDiatomics --name 7net-0_HomonuclearDiatomics
    deps:
    - nodes/initialize/Smiles2Conformers/frames.xyz
    metrics:
    - nodes/7net-0/HomonuclearDiatomics/node-meta.json:
        cache: true
    outs:
    - nodes/7net-0/HomonuclearDiatomics/frames.json
    - nodes/7net-0/HomonuclearDiatomics/model_outs
    - nodes/7net-0/HomonuclearDiatomics/results.csv
    params:
    - 7net-0_HomonuclearDiatomics
  7net-mf-ompa-mpa_HomonuclearDiatomics:
    cmd: zntrack run mlipx.nodes.diatomics.HomonuclearDiatomics --name 7net-mf-ompa-mpa_HomonuclearDiatomics
    deps:
    - nodes/initialize/Smiles2Conformers/frames.xyz
    metrics:
    - nodes/7net-mf-ompa-mpa/HomonuclearDiatomics/node-meta.json:
        cache: true
    outs:
    - nodes/7net-mf-ompa-mpa/HomonuclearDiatomics/frames.json
    - nodes/7net-mf-ompa-mpa/HomonuclearDiatomics/model_outs
    - nodes/7net-mf-ompa-mpa/HomonuclearDiatomics/results.csv
    params:
    - 7net-mf-ompa-mpa_HomonuclearDiatomics
  MACE-MPA-0_HomonuclearDiatomics:
    cmd: zntrack run mlipx.nodes.diatomics.HomonuclearDiatomics --name MACE-MPA-0_HomonuclearDiatomics
    deps:
    - nodes/initialize/Smiles2Conformers/frames.xyz
    metrics:
    - nodes/MACE-MPA-0/HomonuclearDiatomics/node-meta.json:
        cache: true
    outs:
    - nodes/MACE-MPA-0/HomonuclearDiatomics/frames.json
    - nodes/MACE-MPA-0/HomonuclearDiatomics/model_outs
    - nodes/MACE-MPA-0/HomonuclearDiatomics/results.csv
    params:
    - MACE-MPA-0_HomonuclearDiatomics
  initialize_Smiles2Conformers:
    cmd: zntrack run mlipx.nodes.smiles.Smiles2Conformers --name initialize_Smiles2Conformers
    metrics:
    - nodes/initialize/Smiles2Conformers/node-meta.json:
        cache: true
    outs:
    - nodes/initialize/Smiles2Conformers/frames.xyz
    params:
    - initialize_Smiles2Conformers
  mattersim_HomonuclearDiatomics:
    cmd: zntrack run mlipx.nodes.diatomics.HomonuclearDiatomics --name mattersim_HomonuclearDiatomics
    deps:
    - nodes/initialize/Smiles2Conformers/frames.xyz
    metrics:
    - nodes/mattersim/HomonuclearDiatomics/node-meta.json:
        cache: true
    outs:
    - nodes/mattersim/HomonuclearDiatomics/frames.json
    - nodes/mattersim/HomonuclearDiatomics/model_outs
    - nodes/mattersim/HomonuclearDiatomics/results.csv
    params:
    - mattersim_HomonuclearDiatomics
  orb-v2_HomonuclearDiatomics:
    cmd: zntrack run mlipx.nodes.diatomics.HomonuclearDiatomics --name orb-v2_HomonuclearDiatomics
    deps:
    - nodes/initialize/Smiles2Conformers/frames.xyz
    metrics:
    - nodes/orb-v2/HomonuclearDiatomics/node-meta.json:
        cache: true
    outs:
    - nodes/orb-v2/HomonuclearDiatomics/frames.json
    - nodes/orb-v2/HomonuclearDiatomics/model_outs
    - nodes/orb-v2/HomonuclearDiatomics/results.csv
    params:
    - orb-v2_HomonuclearDiatomics
  orb-v3_HomonuclearDiatomics:
    cmd: zntrack run mlipx.nodes.diatomics.HomonuclearDiatomics --name orb-v3_HomonuclearDiatomics
    deps:
    - nodes/initialize/Smiles2Conformers/frames.xyz
    metrics:
    - nodes/orb-v3/HomonuclearDiatomics/node-meta.json:
        cache: true
    outs:
    - nodes/orb-v3/HomonuclearDiatomics/frames.json
    - nodes/orb-v3/HomonuclearDiatomics/model_outs
    - nodes/orb-v3/HomonuclearDiatomics/results.csv
    params:
    - orb-v3_HomonuclearDiatomics
  orca_HomonuclearDiatomics:
    cmd: zntrack run mlipx.nodes.diatomics.HomonuclearDiatomics --name orca_HomonuclearDiatomics
    deps:
    - nodes/initialize/Smiles2Conformers/frames.xyz
    metrics:
    - nodes/orca/HomonuclearDiatomics/node-meta.json:
        cache: true
    outs:
    - nodes/orca/HomonuclearDiatomics/frames.json
    - nodes/orca/HomonuclearDiatomics/model_outs
    - nodes/orca/HomonuclearDiatomics/results.csv
    params:
    - orca_HomonuclearDiatomics
