7net-0_HomonuclearDiatomics:
  elements: []
  eq_distance: covalent-radiuis
  max_distance: 2.0
  min_distance: 0.5
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  n_points: 100
7net-mf-ompa-mpa_HomonuclearDiatomics:
  elements: []
  eq_distance: covalent-radiuis
  max_distance: 2.0
  min_distance: 0.5
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      modal: mpa
      model: 7net-mf-ompa
    module: sevenn.sevennet_calculator
  n_points: 100
MACE-MPA-0_HomonuclearDiatomics:
  elements: []
  eq_distance: covalent-radiuis
  max_distance: 2.0
  min_distance: 0.5
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: ../../models/mace-mpa-0-medium.model
    module: mace.calculators
  n_points: 100
initialize_Smiles2Conformers:
  max_attempts: 1000
  num_confs: 1
  random_seed: 42
  smiles: '[Li+].[Cl-]'
mattersim_HomonuclearDiatomics:
  elements: []
  eq_distance: covalent-radiuis
  max_distance: 2.0
  min_distance: 0.5
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MatterSimCalculator
    device: auto
    kwargs: null
    module: mattersim.forcefield
  n_points: 100
orb-v2_HomonuclearDiatomics:
  elements: []
  eq_distance: covalent-radiuis
  max_distance: 2.0
  min_distance: 0.5
  model:
    _cls: models.OrbCalc
    device: auto
    kwargs: {}
    name: orb_v2
  n_points: 100
orb-v3_HomonuclearDiatomics:
  elements: []
  eq_distance: covalent-radiuis
  max_distance: 2.0
  min_distance: 0.5
  model:
    _cls: models.OrbCalc
    device: auto
    kwargs: {}
    name: orb_v3_conservative_inf_omat
  n_points: 100
orca_HomonuclearDiatomics:
  elements: []
  eq_distance: covalent-radiuis
  max_distance: 2.0
  min_distance: 0.5
  model:
    _cls: mlipx.nodes.orca.OrcaSinglePoint
    orca_shell: null
    orcablocks: '%pal nprocs 8 end'
    orcasimpleinput: PBE def2-TZVP TightSCF EnGrad
  n_points: 100
