plots:
- mace-mpa-0_VibrationalAnalysis_results:
    x:
      nodes/mace-mpa-0/VibrationalAnalysis/results.csv: Frame
    y:
      nodes/mace-mpa-0/VibrationalAnalysis/results.csv: ddG
- 7net-0_VibrationalAnalysis_results:
    x:
      nodes/7net-0/VibrationalAnalysis/results.csv: Frame
    y:
      nodes/7net-0/VibrationalAnalysis/results.csv: ddG
- 7net-mf-ompa-mpa_VibrationalAnalysis_results:
    x:
      nodes/7net-mf-ompa-mpa/VibrationalAnalysis/results.csv: Frame
    y:
      nodes/7net-mf-ompa-mpa/VibrationalAnalysis/results.csv: ddG
- orb-v2_VibrationalAnalysis_results:
    x:
      nodes/orb-v2/VibrationalAnalysis/results.csv: Frame
    y:
      nodes/orb-v2/VibrationalAnalysis/results.csv: ddG
- orb-v3_VibrationalAnalysis_results:
    x:
      nodes/orb-v3/VibrationalAnalysis/results.csv: Frame
    y:
      nodes/orb-v3/VibrationalAnalysis/results.csv: ddG
- mattersim_VibrationalAnalysis_results:
    x:
      nodes/mattersim/VibrationalAnalysis/results.csv: Frame
    y:
      nodes/mattersim/VibrationalAnalysis/results.csv: ddG
- grace-2l-omat_VibrationalAnalysis_results:
    x:
      nodes/grace-2l-omat/VibrationalAnalysis/results.csv: Frame
    y:
      nodes/grace-2l-omat/VibrationalAnalysis/results.csv: ddG
stages:
  7net-0_VibrationalAnalysis:
    cmd: zntrack run mlipx.nodes.vibrational_analysis.VibrationalAnalysis --name 7net-0_VibrationalAnalysis
    deps:
    - nodes/initialize/Smiles2Conformers/frames.xyz
    - nodes/initialize/Smiles2Conformers_1/frames.xyz
    - nodes/initialize/Smiles2Conformers_2/frames.xyz
    - nodes/initialize/Smiles2Conformers_3/frames.xyz
    metrics:
    - nodes/7net-0/VibrationalAnalysis/node-meta.json:
        cache: true
    outs:
    - nodes/7net-0/VibrationalAnalysis/frames.xyz
    - nodes/7net-0/VibrationalAnalysis/modes
    - nodes/7net-0/VibrationalAnalysis/modes.xyz
    - nodes/7net-0/VibrationalAnalysis/results.csv
    - nodes/7net-0/VibrationalAnalysis/vib
    params:
    - 7net-0_VibrationalAnalysis
  7net-mf-ompa-mpa_VibrationalAnalysis:
    cmd: zntrack run mlipx.nodes.vibrational_analysis.VibrationalAnalysis --name 7net-mf-ompa-mpa_VibrationalAnalysis
    deps:
    - nodes/initialize/Smiles2Conformers/frames.xyz
    - nodes/initialize/Smiles2Conformers_1/frames.xyz
    - nodes/initialize/Smiles2Conformers_2/frames.xyz
    - nodes/initialize/Smiles2Conformers_3/frames.xyz
    metrics:
    - nodes/7net-mf-ompa-mpa/VibrationalAnalysis/node-meta.json:
        cache: true
    outs:
    - nodes/7net-mf-ompa-mpa/VibrationalAnalysis/frames.xyz
    - nodes/7net-mf-ompa-mpa/VibrationalAnalysis/modes
    - nodes/7net-mf-ompa-mpa/VibrationalAnalysis/modes.xyz
    - nodes/7net-mf-ompa-mpa/VibrationalAnalysis/results.csv
    - nodes/7net-mf-ompa-mpa/VibrationalAnalysis/vib
    params:
    - 7net-mf-ompa-mpa_VibrationalAnalysis
  grace-2l-omat_VibrationalAnalysis:
    cmd: zntrack run mlipx.nodes.vibrational_analysis.VibrationalAnalysis --name grace-2l-omat_VibrationalAnalysis
    deps:
    - nodes/initialize/Smiles2Conformers/frames.xyz
    - nodes/initialize/Smiles2Conformers_1/frames.xyz
    - nodes/initialize/Smiles2Conformers_2/frames.xyz
    - nodes/initialize/Smiles2Conformers_3/frames.xyz
    metrics:
    - nodes/grace-2l-omat/VibrationalAnalysis/node-meta.json:
        cache: true
    outs:
    - nodes/grace-2l-omat/VibrationalAnalysis/frames.xyz
    - nodes/grace-2l-omat/VibrationalAnalysis/modes
    - nodes/grace-2l-omat/VibrationalAnalysis/modes.xyz
    - nodes/grace-2l-omat/VibrationalAnalysis/results.csv
    - nodes/grace-2l-omat/VibrationalAnalysis/vib
    params:
    - grace-2l-omat_VibrationalAnalysis
  initialize_Smiles2Conformers:
    cmd: zntrack run mlipx.nodes.smiles.Smiles2Conformers --name initialize_Smiles2Conformers
    metrics:
    - nodes/initialize/Smiles2Conformers/node-meta.json:
        cache: true
    outs:
    - nodes/initialize/Smiles2Conformers/frames.xyz
    params:
    - initialize_Smiles2Conformers
  initialize_Smiles2Conformers_1:
    cmd: zntrack run mlipx.nodes.smiles.Smiles2Conformers --name initialize_Smiles2Conformers_1
    metrics:
    - nodes/initialize/Smiles2Conformers_1/node-meta.json:
        cache: true
    outs:
    - nodes/initialize/Smiles2Conformers_1/frames.xyz
    params:
    - initialize_Smiles2Conformers_1
  initialize_Smiles2Conformers_2:
    cmd: zntrack run mlipx.nodes.smiles.Smiles2Conformers --name initialize_Smiles2Conformers_2
    metrics:
    - nodes/initialize/Smiles2Conformers_2/node-meta.json:
        cache: true
    outs:
    - nodes/initialize/Smiles2Conformers_2/frames.xyz
    params:
    - initialize_Smiles2Conformers_2
  initialize_Smiles2Conformers_3:
    cmd: zntrack run mlipx.nodes.smiles.Smiles2Conformers --name initialize_Smiles2Conformers_3
    metrics:
    - nodes/initialize/Smiles2Conformers_3/node-meta.json:
        cache: true
    outs:
    - nodes/initialize/Smiles2Conformers_3/frames.xyz
    params:
    - initialize_Smiles2Conformers_3
  mace-mpa-0_VibrationalAnalysis:
    cmd: zntrack run mlipx.nodes.vibrational_analysis.VibrationalAnalysis --name mace-mpa-0_VibrationalAnalysis
    deps:
    - nodes/initialize/Smiles2Conformers/frames.xyz
    - nodes/initialize/Smiles2Conformers_1/frames.xyz
    - nodes/initialize/Smiles2Conformers_2/frames.xyz
    - nodes/initialize/Smiles2Conformers_3/frames.xyz
    metrics:
    - nodes/mace-mpa-0/VibrationalAnalysis/node-meta.json:
        cache: true
    outs:
    - nodes/mace-mpa-0/VibrationalAnalysis/frames.xyz
    - nodes/mace-mpa-0/VibrationalAnalysis/modes
    - nodes/mace-mpa-0/VibrationalAnalysis/modes.xyz
    - nodes/mace-mpa-0/VibrationalAnalysis/results.csv
    - nodes/mace-mpa-0/VibrationalAnalysis/vib
    params:
    - mace-mpa-0_VibrationalAnalysis
  mattersim_VibrationalAnalysis:
    cmd: zntrack run mlipx.nodes.vibrational_analysis.VibrationalAnalysis --name mattersim_VibrationalAnalysis
    deps:
    - nodes/initialize/Smiles2Conformers/frames.xyz
    - nodes/initialize/Smiles2Conformers_1/frames.xyz
    - nodes/initialize/Smiles2Conformers_2/frames.xyz
    - nodes/initialize/Smiles2Conformers_3/frames.xyz
    metrics:
    - nodes/mattersim/VibrationalAnalysis/node-meta.json:
        cache: true
    outs:
    - nodes/mattersim/VibrationalAnalysis/frames.xyz
    - nodes/mattersim/VibrationalAnalysis/modes
    - nodes/mattersim/VibrationalAnalysis/modes.xyz
    - nodes/mattersim/VibrationalAnalysis/results.csv
    - nodes/mattersim/VibrationalAnalysis/vib
    params:
    - mattersim_VibrationalAnalysis
  orb-v2_VibrationalAnalysis:
    cmd: zntrack run mlipx.nodes.vibrational_analysis.VibrationalAnalysis --name orb-v2_VibrationalAnalysis
    deps:
    - nodes/initialize/Smiles2Conformers/frames.xyz
    - nodes/initialize/Smiles2Conformers_1/frames.xyz
    - nodes/initialize/Smiles2Conformers_2/frames.xyz
    - nodes/initialize/Smiles2Conformers_3/frames.xyz
    metrics:
    - nodes/orb-v2/VibrationalAnalysis/node-meta.json:
        cache: true
    outs:
    - nodes/orb-v2/VibrationalAnalysis/frames.xyz
    - nodes/orb-v2/VibrationalAnalysis/modes
    - nodes/orb-v2/VibrationalAnalysis/modes.xyz
    - nodes/orb-v2/VibrationalAnalysis/results.csv
    - nodes/orb-v2/VibrationalAnalysis/vib
    params:
    - orb-v2_VibrationalAnalysis
  orb-v3_VibrationalAnalysis:
    cmd: zntrack run mlipx.nodes.vibrational_analysis.VibrationalAnalysis --name orb-v3_VibrationalAnalysis
    deps:
    - nodes/initialize/Smiles2Conformers/frames.xyz
    - nodes/initialize/Smiles2Conformers_1/frames.xyz
    - nodes/initialize/Smiles2Conformers_2/frames.xyz
    - nodes/initialize/Smiles2Conformers_3/frames.xyz
    metrics:
    - nodes/orb-v3/VibrationalAnalysis/node-meta.json:
        cache: true
    outs:
    - nodes/orb-v3/VibrationalAnalysis/frames.xyz
    - nodes/orb-v3/VibrationalAnalysis/modes
    - nodes/orb-v3/VibrationalAnalysis/modes.xyz
    - nodes/orb-v3/VibrationalAnalysis/results.csv
    - nodes/orb-v3/VibrationalAnalysis/vib
    params:
    - orb-v3_VibrationalAnalysis
