7net-0_VibrationalAnalysis:
  calc_type: null
  displacement: 0.015
  free_indices: null
  lower_freq_threshold: 12
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  nfree: 4
  system: molecule
  temperature: 298.15
7net-mf-ompa-mpa_VibrationalAnalysis:
  calc_type: null
  displacement: 0.015
  free_indices: null
  lower_freq_threshold: 12
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      modal: mpa
      model: 7net-mf-ompa
    module: sevenn.sevennet_calculator
  nfree: 4
  system: molecule
  temperature: 298.15
GRACE-2L-OMAT_VibrationalAnalysis:
  calc_type: null
  displacement: 0.015
  free_indices: null
  lower_freq_threshold: 12
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: TPCalculator
    device: null
    kwargs:
      model: ../../models/GRACE-2L-OMAT
    module: tensorpotential.calculator
  nfree: 4
  system: molecule
  temperature: 298.15
MACE-MPA-0_VibrationalAnalysis:
  calc_type: null
  displacement: 0.015
  free_indices: null
  lower_freq_threshold: 12
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: ../../models/mace-mpa-0-medium.model
    module: mace.calculators
  nfree: 4
  system: molecule
  temperature: 298.15
initialize_Smiles2Conformers:
  max_attempts: 1000
  num_confs: 1
  random_seed: 42
  smiles: CO
initialize_Smiles2Conformers_1:
  max_attempts: 1000
  num_confs: 1
  random_seed: 42
  smiles: CCO
initialize_Smiles2Conformers_2:
  max_attempts: 1000
  num_confs: 1
  random_seed: 42
  smiles: CCCO
initialize_Smiles2Conformers_3:
  max_attempts: 1000
  num_confs: 1
  random_seed: 42
  smiles: CCCCO
mattersim_VibrationalAnalysis:
  calc_type: null
  displacement: 0.015
  free_indices: null
  lower_freq_threshold: 12
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MatterSimCalculator
    device: auto
    kwargs: null
    module: mattersim.forcefield
  nfree: 4
  system: molecule
  temperature: 298.15
orb-v2_VibrationalAnalysis:
  calc_type: null
  displacement: 0.015
  free_indices: null
  lower_freq_threshold: 12
  model:
    _cls: models.OrbCalc
    device: auto
    kwargs: {}
    name: orb_v2
  nfree: 4
  system: molecule
  temperature: 298.15
orb-v3_VibrationalAnalysis:
  calc_type: null
  displacement: 0.015
  free_indices: null
  lower_freq_threshold: 12
  model:
    _cls: models.OrbCalc
    device: auto
    kwargs: {}
    name: orb_v3_conservative_inf_omat
  nfree: 4
  system: molecule
  temperature: 298.15
