chgnet_0_PhaseDiagram:
  chemsys: null
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: CHGNetCalculator
    device: null
    kwargs: null
    module: chgnet.model
initialize_MPRester:
  search_kwargs:
    material_ids:
    - mp-30084
mace_mp_0_PhaseDiagram:
  chemsys: null
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: medium
    module: mace.calculators
mattersim_0_PhaseDiagram:
  chemsys: null
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MatterSimCalculator
    device: auto
    kwargs: null
    module: mattersim.forcefield
orb_v2_0_PhaseDiagram:
  chemsys: null
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: models.OrbCalc
    device: auto
    name: orb_v2
sevennet_0_PhaseDiagram:
  chemsys: null
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
