plots:
- MACE-MPA-0_0_EnergyVolumeCurve_results:
    x:
      nodes/MACE-MPA-0/0/EnergyVolumeCurve/results.csv: scale
    y:
      nodes/MACE-MPA-0/0/EnergyVolumeCurve/results.csv: energy
- 7net-0_0_EnergyVolumeCurve_results:
    x:
      nodes/7net-0/0/EnergyVolumeCurve/results.csv: scale
    y:
      nodes/7net-0/0/EnergyVolumeCurve/results.csv: energy
- 7net-mf-ompa-mpa_0_EnergyVolumeCurve_results:
    x:
      nodes/7net-mf-ompa-mpa/0/EnergyVolumeCurve/results.csv: scale
    y:
      nodes/7net-mf-ompa-mpa/0/EnergyVolumeCurve/results.csv: energy
- orb-v2_0_EnergyVolumeCurve_results:
    x:
      nodes/orb-v2/0/EnergyVolumeCurve/results.csv: scale
    y:
      nodes/orb-v2/0/EnergyVolumeCurve/results.csv: energy
- orb-v3_0_EnergyVolumeCurve_results:
    x:
      nodes/orb-v3/0/EnergyVolumeCurve/results.csv: scale
    y:
      nodes/orb-v3/0/EnergyVolumeCurve/results.csv: energy
- mattersim_0_EnergyVolumeCurve_results:
    x:
      nodes/mattersim/0/EnergyVolumeCurve/results.csv: scale
    y:
      nodes/mattersim/0/EnergyVolumeCurve/results.csv: energy
- GRACE-2L-OMAT_0_EnergyVolumeCurve_results:
    x:
      nodes/GRACE-2L-OMAT/0/EnergyVolumeCurve/results.csv: scale
    y:
      nodes/GRACE-2L-OMAT/0/EnergyVolumeCurve/results.csv: energy
- chgnet_0_EnergyVolumeCurve_results:
    x:
      nodes/chgnet/0/EnergyVolumeCurve/results.csv: scale
    y:
      nodes/chgnet/0/EnergyVolumeCurve/results.csv: energy
stages:
  7net-0_0_EnergyVolumeCurve:
    cmd: zntrack run mlipx.nodes.energy_volume.EnergyVolumeCurve --name 7net-0_0_EnergyVolumeCurve
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/7net-0/0/EnergyVolumeCurve/node-meta.json:
        cache: true
    outs:
    - nodes/7net-0/0/EnergyVolumeCurve/frames.xyz
    - nodes/7net-0/0/EnergyVolumeCurve/results.csv
    params:
    - 7net-0_0_EnergyVolumeCurve
  7net-mf-ompa-mpa_0_EnergyVolumeCurve:
    cmd: zntrack run mlipx.nodes.energy_volume.EnergyVolumeCurve --name 7net-mf-ompa-mpa_0_EnergyVolumeCurve
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/7net-mf-ompa-mpa/0/EnergyVolumeCurve/node-meta.json:
        cache: true
    outs:
    - nodes/7net-mf-ompa-mpa/0/EnergyVolumeCurve/frames.xyz
    - nodes/7net-mf-ompa-mpa/0/EnergyVolumeCurve/results.csv
    params:
    - 7net-mf-ompa-mpa_0_EnergyVolumeCurve
  GRACE-2L-OMAT_0_EnergyVolumeCurve:
    cmd: zntrack run mlipx.nodes.energy_volume.EnergyVolumeCurve --name GRACE-2L-OMAT_0_EnergyVolumeCurve
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/GRACE-2L-OMAT/0/EnergyVolumeCurve/node-meta.json:
        cache: true
    outs:
    - nodes/GRACE-2L-OMAT/0/EnergyVolumeCurve/frames.xyz
    - nodes/GRACE-2L-OMAT/0/EnergyVolumeCurve/results.csv
    params:
    - GRACE-2L-OMAT_0_EnergyVolumeCurve
  MACE-MPA-0_0_EnergyVolumeCurve:
    cmd: zntrack run mlipx.nodes.energy_volume.EnergyVolumeCurve --name MACE-MPA-0_0_EnergyVolumeCurve
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/MACE-MPA-0/0/EnergyVolumeCurve/node-meta.json:
        cache: true
    outs:
    - nodes/MACE-MPA-0/0/EnergyVolumeCurve/frames.xyz
    - nodes/MACE-MPA-0/0/EnergyVolumeCurve/results.csv
    params:
    - MACE-MPA-0_0_EnergyVolumeCurve
  chgnet_0_EnergyVolumeCurve:
    cmd: zntrack run mlipx.nodes.energy_volume.EnergyVolumeCurve --name chgnet_0_EnergyVolumeCurve
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/chgnet/0/EnergyVolumeCurve/node-meta.json:
        cache: true
    outs:
    - nodes/chgnet/0/EnergyVolumeCurve/frames.xyz
    - nodes/chgnet/0/EnergyVolumeCurve/results.csv
    params:
    - chgnet_0_EnergyVolumeCurve
  initialize_MPRester:
    cmd: zntrack run mlipx.nodes.mp_api.MPRester --name initialize_MPRester
    metrics:
    - nodes/initialize/MPRester/node-meta.json:
        cache: true
    outs:
    - nodes/initialize/MPRester/frames.xyz
    params:
    - initialize_MPRester
  mattersim_0_EnergyVolumeCurve:
    cmd: zntrack run mlipx.nodes.energy_volume.EnergyVolumeCurve --name mattersim_0_EnergyVolumeCurve
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/mattersim/0/EnergyVolumeCurve/node-meta.json:
        cache: true
    outs:
    - nodes/mattersim/0/EnergyVolumeCurve/frames.xyz
    - nodes/mattersim/0/EnergyVolumeCurve/results.csv
    params:
    - mattersim_0_EnergyVolumeCurve
  orb-v2_0_EnergyVolumeCurve:
    cmd: zntrack run mlipx.nodes.energy_volume.EnergyVolumeCurve --name orb-v2_0_EnergyVolumeCurve
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/orb-v2/0/EnergyVolumeCurve/node-meta.json:
        cache: true
    outs:
    - nodes/orb-v2/0/EnergyVolumeCurve/frames.xyz
    - nodes/orb-v2/0/EnergyVolumeCurve/results.csv
    params:
    - orb-v2_0_EnergyVolumeCurve
  orb-v3_0_EnergyVolumeCurve:
    cmd: zntrack run mlipx.nodes.energy_volume.EnergyVolumeCurve --name orb-v3_0_EnergyVolumeCurve
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/orb-v3/0/EnergyVolumeCurve/node-meta.json:
        cache: true
    outs:
    - nodes/orb-v3/0/EnergyVolumeCurve/frames.xyz
    - nodes/orb-v3/0/EnergyVolumeCurve/results.csv
    params:
    - orb-v3_0_EnergyVolumeCurve
