7net-0_0_EnergyVolumeCurve:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  n_points: 50
  start: 0.8
  stop: 2.0
7net-mf-ompa-mpa_0_EnergyVolumeCurve:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      modal: mpa
      model: 7net-mf-ompa
    module: sevenn.sevennet_calculator
  n_points: 50
  start: 0.8
  stop: 2.0
chgnet_0_EnergyVolumeCurve:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: CHGNetCalculator
    device: null
    kwargs: null
    module: chgnet.model
  n_points: 50
  start: 0.8
  stop: 2.0
grace-2l-omat_0_EnergyVolumeCurve:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: TPCalculator
    device: null
    kwargs:
      model: ../../models/GRACE-2L-OMAT
    module: tensorpotential.calculator
  n_points: 50
  start: 0.8
  stop: 2.0
initialize_MPRester:
  search_kwargs:
    material_ids:
    - mp-1143
mace-mpa-0_0_EnergyVolumeCurve:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: ../../models/mace-mpa-0-medium.model
    module: mace.calculators
  n_points: 50
  start: 0.8
  stop: 2.0
mattersim_0_EnergyVolumeCurve:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MatterSimCalculator
    device: auto
    kwargs: null
    module: mattersim.forcefield
  n_points: 50
  start: 0.8
  stop: 2.0
orb-v2_0_EnergyVolumeCurve:
  data_id: -1
  model:
    _cls: models.OrbCalc
    device: auto
    kwargs: {}
    name: orb_v2
  n_points: 50
  start: 0.8
  stop: 2.0
orb-v3_0_EnergyVolumeCurve:
  data_id: -1
  model:
    _cls: models.OrbCalc
    device: auto
    kwargs: {}
    name: orb_v3_conservative_inf_omat
  n_points: 50
  start: 0.8
  stop: 2.0
