plots:
- mace-mpa-0_0_PhaseDiagram_results:
    x:
      nodes/mace-mpa-0/0/PhaseDiagram/results.csv: data_id
    y:
      nodes/mace-mpa-0/0/PhaseDiagram/results.csv: formation_energy
- 7net-0_0_PhaseDiagram_results:
    x:
      nodes/7net-0/0/PhaseDiagram/results.csv: data_id
    y:
      nodes/7net-0/0/PhaseDiagram/results.csv: formation_energy
- 7net-mf-ompa-mpa_0_PhaseDiagram_results:
    x:
      nodes/7net-mf-ompa-mpa/0/PhaseDiagram/results.csv: data_id
    y:
      nodes/7net-mf-ompa-mpa/0/PhaseDiagram/results.csv: formation_energy
- orb-v2_0_PhaseDiagram_results:
    x:
      nodes/orb-v2/0/PhaseDiagram/results.csv: data_id
    y:
      nodes/orb-v2/0/PhaseDiagram/results.csv: formation_energy
- orb-v3_0_PhaseDiagram_results:
    x:
      nodes/orb-v3/0/PhaseDiagram/results.csv: data_id
    y:
      nodes/orb-v3/0/PhaseDiagram/results.csv: formation_energy
- mattersim_0_PhaseDiagram_results:
    x:
      nodes/mattersim/0/PhaseDiagram/results.csv: data_id
    y:
      nodes/mattersim/0/PhaseDiagram/results.csv: formation_energy
- grace-2l-omat_0_PhaseDiagram_results:
    x:
      nodes/grace-2l-omat/0/PhaseDiagram/results.csv: data_id
    y:
      nodes/grace-2l-omat/0/PhaseDiagram/results.csv: formation_energy
- chgnet_0_PhaseDiagram_results:
    x:
      nodes/chgnet/0/PhaseDiagram/results.csv: data_id
    y:
      nodes/chgnet/0/PhaseDiagram/results.csv: formation_energy
stages:
  7net-0_0_PhaseDiagram:
    cmd: zntrack run mlipx.nodes.phase_diagram.PhaseDiagram --name 7net-0_0_PhaseDiagram
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/7net-0/0/PhaseDiagram/node-meta.json:
        cache: true
    outs:
    - nodes/7net-0/0/PhaseDiagram/frames.xyz
    - nodes/7net-0/0/PhaseDiagram/phase_diagram.json
    - nodes/7net-0/0/PhaseDiagram/results.csv
    params:
    - 7net-0_0_PhaseDiagram
  7net-mf-ompa-mpa_0_PhaseDiagram:
    cmd: zntrack run mlipx.nodes.phase_diagram.PhaseDiagram --name 7net-mf-ompa-mpa_0_PhaseDiagram
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/7net-mf-ompa-mpa/0/PhaseDiagram/node-meta.json:
        cache: true
    outs:
    - nodes/7net-mf-ompa-mpa/0/PhaseDiagram/frames.xyz
    - nodes/7net-mf-ompa-mpa/0/PhaseDiagram/phase_diagram.json
    - nodes/7net-mf-ompa-mpa/0/PhaseDiagram/results.csv
    params:
    - 7net-mf-ompa-mpa_0_PhaseDiagram
  chgnet_0_PhaseDiagram:
    cmd: zntrack run mlipx.nodes.phase_diagram.PhaseDiagram --name chgnet_0_PhaseDiagram
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/chgnet/0/PhaseDiagram/node-meta.json:
        cache: true
    outs:
    - nodes/chgnet/0/PhaseDiagram/frames.xyz
    - nodes/chgnet/0/PhaseDiagram/phase_diagram.json
    - nodes/chgnet/0/PhaseDiagram/results.csv
    params:
    - chgnet_0_PhaseDiagram
  grace-2l-omat_0_PhaseDiagram:
    cmd: zntrack run mlipx.nodes.phase_diagram.PhaseDiagram --name grace-2l-omat_0_PhaseDiagram
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/grace-2l-omat/0/PhaseDiagram/node-meta.json:
        cache: true
    outs:
    - nodes/grace-2l-omat/0/PhaseDiagram/frames.xyz
    - nodes/grace-2l-omat/0/PhaseDiagram/phase_diagram.json
    - nodes/grace-2l-omat/0/PhaseDiagram/results.csv
    params:
    - grace-2l-omat_0_PhaseDiagram
  initialize_MPRester:
    cmd: zntrack run mlipx.nodes.mp_api.MPRester --name initialize_MPRester
    metrics:
    - nodes/initialize/MPRester/node-meta.json:
        cache: true
    outs:
    - nodes/initialize/MPRester/frames.xyz
    params:
    - initialize_MPRester
  mace-mpa-0_0_PhaseDiagram:
    cmd: zntrack run mlipx.nodes.phase_diagram.PhaseDiagram --name mace-mpa-0_0_PhaseDiagram
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/mace-mpa-0/0/PhaseDiagram/node-meta.json:
        cache: true
    outs:
    - nodes/mace-mpa-0/0/PhaseDiagram/frames.xyz
    - nodes/mace-mpa-0/0/PhaseDiagram/phase_diagram.json
    - nodes/mace-mpa-0/0/PhaseDiagram/results.csv
    params:
    - mace-mpa-0_0_PhaseDiagram
  mattersim_0_PhaseDiagram:
    cmd: zntrack run mlipx.nodes.phase_diagram.PhaseDiagram --name mattersim_0_PhaseDiagram
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/mattersim/0/PhaseDiagram/node-meta.json:
        cache: true
    outs:
    - nodes/mattersim/0/PhaseDiagram/frames.xyz
    - nodes/mattersim/0/PhaseDiagram/phase_diagram.json
    - nodes/mattersim/0/PhaseDiagram/results.csv
    params:
    - mattersim_0_PhaseDiagram
  orb-v2_0_PhaseDiagram:
    cmd: zntrack run mlipx.nodes.phase_diagram.PhaseDiagram --name orb-v2_0_PhaseDiagram
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/orb-v2/0/PhaseDiagram/node-meta.json:
        cache: true
    outs:
    - nodes/orb-v2/0/PhaseDiagram/frames.xyz
    - nodes/orb-v2/0/PhaseDiagram/phase_diagram.json
    - nodes/orb-v2/0/PhaseDiagram/results.csv
    params:
    - orb-v2_0_PhaseDiagram
  orb-v3_0_PhaseDiagram:
    cmd: zntrack run mlipx.nodes.phase_diagram.PhaseDiagram --name orb-v3_0_PhaseDiagram
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/orb-v3/0/PhaseDiagram/node-meta.json:
        cache: true
    outs:
    - nodes/orb-v3/0/PhaseDiagram/frames.xyz
    - nodes/orb-v3/0/PhaseDiagram/phase_diagram.json
    - nodes/orb-v3/0/PhaseDiagram/results.csv
    params:
    - orb-v3_0_PhaseDiagram
