7net-0_0_PhaseDiagram:
  chemsys: null
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
7net-mf-ompa-mpa_0_PhaseDiagram:
  chemsys: null
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      modal: mpa
      model: 7net-mf-ompa
    module: sevenn.sevennet_calculator
chgnet_0_PhaseDiagram:
  chemsys: null
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: CHGNetCalculator
    device: null
    kwargs: null
    module: chgnet.model
grace-2l-omat_0_PhaseDiagram:
  chemsys: null
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: TPCalculator
    device: null
    kwargs:
      model: ../../models/GRACE-2L-OMAT
    module: tensorpotential.calculator
initialize_MPRester:
  search_kwargs:
    material_ids:
    - mp-30084
mace-mpa-0_0_PhaseDiagram:
  chemsys: null
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: ../../models/mace-mpa-0-medium.model
    module: mace.calculators
mattersim_0_PhaseDiagram:
  chemsys: null
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MatterSimCalculator
    device: auto
    kwargs: null
    module: mattersim.forcefield
orb-v2_0_PhaseDiagram:
  chemsys: null
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: models.OrbCalc
    device: auto
    kwargs: {}
    name: orb_v2
orb-v3_0_PhaseDiagram:
  chemsys: null
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: models.OrbCalc
    device: auto
    kwargs: {}
    name: orb_v3_conservative_inf_omat
