chgnet_0_PermutationInvariance:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: CHGNetCalculator
    device: null
    kwargs: null
    module: chgnet.model
  n_points: 100
chgnet_0_RotationalInvariance:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: CHGNetCalculator
    device: null
    kwargs: null
    module: chgnet.model
  n_points: 100
chgnet_0_TranslationalInvariance:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: CHGNetCalculator
    device: null
    kwargs: null
    module: chgnet.model
  n_points: 100
initialize_MPRester:
  search_kwargs:
    material_ids:
    - mp-1143
mace_mp_0_PermutationInvariance:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: medium
    module: mace.calculators
  n_points: 100
mace_mp_0_RotationalInvariance:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: medium
    module: mace.calculators
  n_points: 100
mace_mp_0_TranslationalInvariance:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: medium
    module: mace.calculators
  n_points: 100
orb_v2_0_PermutationInvariance:
  data_id: -1
  model:
    _cls: models.OrbCalc
    device: auto
    name: orb_v2
  n_points: 100
orb_v2_0_RotationalInvariance:
  data_id: -1
  model:
    _cls: models.OrbCalc
    device: auto
    name: orb_v2
  n_points: 100
orb_v2_0_TranslationalInvariance:
  data_id: -1
  model:
    _cls: models.OrbCalc
    device: auto
    name: orb_v2
  n_points: 100
sevennet_0_PermutationInvariance:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  n_points: 100
sevennet_0_RotationalInvariance:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  n_points: 100
sevennet_0_TranslationalInvariance:
  data_id: -1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  n_points: 100
